library(reshape2)

b_hhold_train<-read.csv('B_hhold_train.csv')
b_indiv_train<-read.csv('B_indiv_train.csv')

#write.csv(names(b_indiv_train),'b_names.csv',row.names = F)
lapply(b_indiv_train, class)
write.csv(lapply(b_indiv_train, class),'b1_names.csv',row.names = F)
data_MmKGUOrD<-dcast(b_indiv_train,id~MmKGUOrD,value.var="iid")
data_splgBZfe<-dcast(b_indiv_train,id~splgBZfe,value.var="iid")
data_JTCCBpjX<-dcast(b_indiv_train,id~JTCCBpjX,value.var="iid")
data_akGaJaYF<-dcast(b_indiv_train,id~akGaJaYF,value.var="iid")
data_eYoMkEyN<-dcast(b_indiv_train,id~eYoMkEyN,value.var="iid")
data_bmhTgzYu<-dcast(b_indiv_train,id~bmhTgzYu,value.var="iid")
data_GjxOmHgp<-dcast(b_indiv_train,id~GjxOmHgp,value.var="iid")
data_mYMBWfIH<-dcast(b_indiv_train,id~mYMBWfIH,value.var="iid")
data_SZucUQmM<-dcast(b_indiv_train,id~SZucUQmM,value.var="iid")
data_EfqFGRSF<-dcast(b_indiv_train,id~EfqFGRSF,value.var="iid")
data_plDSQDzp<-dcast(b_indiv_train,id~plDSQDzp,value.var="iid")
data_jyZvBZlo<-dcast(b_indiv_train,id~jyZvBZlo,value.var="iid")
data_gyxBUEPe<-dcast(b_indiv_train,id~gyxBUEPe,value.var="iid")
data_lTdxcpBA<-dcast(b_indiv_train,id~lTdxcpBA,value.var="iid")
data_yoijDqAm<-dcast(b_indiv_train,id~yoijDqAm,value.var="iid")
data_LkhgHzsx<-dcast(b_indiv_train,id~LkhgHzsx,value.var="iid")
data_UUYXAsfo<-dcast(b_indiv_train,id~UUYXAsfo,value.var="iid")
data_IPBrAaYt<-dcast(b_indiv_train,id~IPBrAaYt,value.var="iid")
data_hCgDHGEc<-dcast(b_indiv_train,id~hCgDHGEc,value.var="iid")
data_GFXSuQvB<-dcast(b_indiv_train,id~GFXSuQvB,value.var="iid")
data_UPtsFglH<-dcast(b_indiv_train,id~UPtsFglH,value.var="iid")
data_HZEsXrsF<-dcast(b_indiv_train,id~HZEsXrsF,value.var="iid")
data_kgVoFHRj<-dcast(b_indiv_train,id~kgVoFHRj,value.var="iid")
data_pqbNHKuK<-dcast(b_indiv_train,id~pqbNHKuK,value.var="iid")
data_gEqzZWXR<-dcast(b_indiv_train,id~gEqzZWXR,value.var="iid")
data_UkXhNUcd<-dcast(b_indiv_train,id~UkXhNUcd,value.var="iid")
data_hggXZmdr<-dcast(b_indiv_train,id~hggXZmdr,value.var="iid")
data_uyhBLPFL<-dcast(b_indiv_train,id~uyhBLPFL,value.var="iid")
data_hwJpBxAl<-dcast(b_indiv_train,id~hwJpBxAl,value.var="iid")
data_BXZfamTt<-dcast(b_indiv_train,id~BXZfamTt,value.var="iid")
data_jkutpUMt<-dcast(b_indiv_train,id~jkutpUMt,value.var="iid")
data_lFkBekuJ<-dcast(b_indiv_train,id~lFkBekuJ,value.var="iid")
data_aTEyAdSs<-dcast(b_indiv_train,id~aTEyAdSs,value.var="iid")
data_TdfmGIAn<-dcast(b_indiv_train,id~TdfmGIAn,value.var="iid")
data_kaVnoUbJ<-dcast(b_indiv_train,id~kaVnoUbJ,value.var="iid")
data_bngqQTHD<-dcast(b_indiv_train,id~bngqQTHD,value.var="iid")
data_cRQWeYKZ<-dcast(b_indiv_train,id~cRQWeYKZ,value.var="iid")
data_ErqgHOEp<-dcast(b_indiv_train,id~ErqgHOEp,value.var="iid")
data_Ftzawcsw<-dcast(b_indiv_train,id~Ftzawcsw,value.var="iid")
data_SlqMdbUr<-dcast(b_indiv_train,id~SlqMdbUr,value.var="iid")
data_jyLFRgZs<-dcast(b_indiv_train,id~jyLFRgZs,value.var="iid")
data_TsredPtf<-dcast(b_indiv_train,id~TsredPtf,value.var="iid")
data_pFOEMbYu<-dcast(b_indiv_train,id~pFOEMbYu,value.var="iid")
data_nOoTxqCQ<-dcast(b_indiv_train,id~nOoTxqCQ,value.var="iid")
data_xohFWnds<-dcast(b_indiv_train,id~xohFWnds,value.var="iid")
data_JYKPCImt<-dcast(b_indiv_train,id~JYKPCImt,value.var="iid")
data_wEtnhPQs<-dcast(b_indiv_train,id~wEtnhPQs,value.var="iid")
data_LIoTrAzw<-dcast(b_indiv_train,id~LIoTrAzw,value.var="iid")
data_IoJgECCi<-dcast(b_indiv_train,id~IoJgECCi,value.var="iid")
data_YwcPaCNf<-dcast(b_indiv_train,id~YwcPaCNf,value.var="iid")
data_PgXpVWEU<-dcast(b_indiv_train,id~PgXpVWEU,value.var="iid")
data_ENQEzjVj<-dcast(b_indiv_train,id~ENQEzjVj,value.var="iid")
data_RFLvRzHv<-dcast(b_indiv_train,id~RFLvRzHv,value.var="iid")
data_xhqvDVIs<-dcast(b_indiv_train,id~xhqvDVIs,value.var="iid")
data_YhbMdUgd<-dcast(b_indiv_train,id~YhbMdUgd,value.var="iid")
data_cPHgLSMk<-dcast(b_indiv_train,id~cPHgLSMk,value.var="iid")
data_jBZoYONA<-dcast(b_indiv_train,id~jBZoYONA,value.var="iid")
data_HHbZiXXp<-dcast(b_indiv_train,id~HHbZiXXp,value.var="iid")
data_DsHJnzeZ<-dcast(b_indiv_train,id~DsHJnzeZ,value.var="iid")
data_PwxicsdL<-dcast(b_indiv_train,id~PwxicsdL,value.var="iid")
data_UZLkbGnz<-dcast(b_indiv_train,id~UZLkbGnz,value.var="iid")
data_xNhKVNgq<-dcast(b_indiv_train,id~xNhKVNgq,value.var="iid")
data_nIgKFReH<-dcast(b_indiv_train,id~nIgKFReH,value.var="iid")
data_FgnMveDS<-dcast(b_indiv_train,id~FgnMveDS,value.var="iid")
data_NdBZKehA<-dcast(b_indiv_train,id~NdBZKehA,value.var="iid")
data_mlyFwTHy<-dcast(b_indiv_train,id~mlyFwTHy,value.var="iid")
data_KjMhhJdX<-dcast(b_indiv_train,id~KjMhhJdX,value.var="iid")
data_zXonuRgn<-dcast(b_indiv_train,id~zXonuRgn,value.var="iid")
data_MWVlKQoo<-dcast(b_indiv_train,id~MWVlKQoo,value.var="iid")
data_mQezyEOr<-dcast(b_indiv_train,id~mQezyEOr,value.var="iid")
data_nPlbGBjS<-dcast(b_indiv_train,id~nPlbGBjS,value.var="iid")
data_nmrQVORl<-dcast(b_indiv_train,id~nmrQVORl,value.var="iid")
data_KGtdytLE<-dcast(b_indiv_train,id~KGtdytLE,value.var="iid")
data_DELHTNkd<-dcast(b_indiv_train,id~DELHTNkd,value.var="iid")
data_rZfVzfDA<-dcast(b_indiv_train,id~rZfVzfDA,value.var="iid")
data_ZHOSEFIu<-dcast(b_indiv_train,id~ZHOSEFIu,value.var="iid")
data_ogUWmSXZ<-dcast(b_indiv_train,id~ogUWmSXZ,value.var="iid")
data_VWMwzteg<-dcast(b_indiv_train,id~VWMwzteg,value.var="iid")
data_HaaXLOfY<-dcast(b_indiv_train,id~HaaXLOfY,value.var="iid")
data_NCyUzkfp<-dcast(b_indiv_train,id~NCyUzkfp,value.var="iid")
data_nAjgFRel<-dcast(b_indiv_train,id~nAjgFRel,value.var="iid")
data_XZUEzGLM<-dcast(b_indiv_train,id~XZUEzGLM,value.var="iid")
data_OFkIQOzS<-dcast(b_indiv_train,id~OFkIQOzS,value.var="iid")
data_BqXRUQgi<-dcast(b_indiv_train,id~BqXRUQgi,value.var="iid")
data_ywnHMkvq<-dcast(b_indiv_train,id~ywnHMkvq,value.var="iid")
data_eKkwQtwX<-dcast(b_indiv_train,id~eKkwQtwX,value.var="iid")
data_fwRLKHlN<-dcast(b_indiv_train,id~fwRLKHlN,value.var="iid")
data_jUwlkffQ<-dcast(b_indiv_train,id~jUwlkffQ,value.var="iid")
data_DAeoUuuN<-dcast(b_indiv_train,id~DAeoUuuN,value.var="iid")
data_gsofZtJJ<-dcast(b_indiv_train,id~gsofZtJJ,value.var="iid")
data_HQPtUibh<-dcast(b_indiv_train,id~HQPtUibh,value.var="iid")
data_aqYWloSo<-dcast(b_indiv_train,id~aqYWloSo,value.var="iid")
data_RUTkmJrl<-dcast(b_indiv_train,id~RUTkmJrl,value.var="iid")
data_tQzcGkNE<-dcast(b_indiv_train,id~tQzcGkNE,value.var="iid")
data_VszNwfYx<-dcast(b_indiv_train,id~VszNwfYx,value.var="iid")
data_hnwVYJyV<-dcast(b_indiv_train,id~hnwVYJyV,value.var="iid")
data_RsMBXisy<-dcast(b_indiv_train,id~RsMBXisy,value.var="iid")
data_MiGIkxpV<-dcast(b_indiv_train,id~MiGIkxpV,value.var="iid")
data_xbOnnZEV<-dcast(b_indiv_train,id~xbOnnZEV,value.var="iid")
data_cGaHwCJA<-dcast(b_indiv_train,id~cGaHwCJA,value.var="iid")
data_dfchpzYE<-dcast(b_indiv_train,id~dfchpzYE,value.var="iid")
data_fwBNLzWK<-dcast(b_indiv_train,id~fwBNLzWK,value.var="iid")
data_lLoRmWKX<-dcast(b_indiv_train,id~lLoRmWKX,value.var="iid")
data_GhzvKcjl<-dcast(b_indiv_train,id~GhzvKcjl,value.var="iid")
data_EpWsJmrF<-dcast(b_indiv_train,id~EpWsJmrF,value.var="iid")
data_wpoJgbis<-dcast(b_indiv_train,id~wpoJgbis,value.var="iid")
data_KyTRKtbW<-dcast(b_indiv_train,id~KyTRKtbW,value.var="iid")
data_xlJGUBXM<-dcast(b_indiv_train,id~xlJGUBXM,value.var="iid")
data_zuvYUDSL<-dcast(b_indiv_train,id~zuvYUDSL,value.var="iid")
data_ozvFfhhM<-dcast(b_indiv_train,id~ozvFfhhM,value.var="iid")
data_ljaNZowA<-dcast(b_indiv_train,id~ljaNZowA,value.var="iid")
data_sbjoLEKh<-dcast(b_indiv_train,id~sbjoLEKh,value.var="iid")
data_pyvZUOyi<-dcast(b_indiv_train,id~pyvZUOyi,value.var="iid")
data_FldbnriM<-dcast(b_indiv_train,id~FldbnriM,value.var="iid")
data_FyXQULwx<-dcast(b_indiv_train,id~FyXQULwx,value.var="iid")
data_UUYYcars<-dcast(b_indiv_train,id~UUYYcars,value.var="iid")
data_xMysunyA<-dcast(b_indiv_train,id~xMysunyA,value.var="iid")
data_FOIfEcny<-dcast(b_indiv_train,id~FOIfEcny,value.var="iid")
data_BhPvRtpj<-dcast(b_indiv_train,id~BhPvRtpj,value.var="iid")
data_JniMXoSr<-dcast(b_indiv_train,id~JniMXoSr,value.var="iid")
data_AFSIVjPG<-dcast(b_indiv_train,id~AFSIVjPG,value.var="iid")
data_lnMlvpes<-dcast(b_indiv_train,id~lnMlvpes,value.var="iid")
data_HrXGKbwr<-dcast(b_indiv_train,id~HrXGKbwr,value.var="iid")
data_NUefhhHz<-dcast(b_indiv_train,id~NUefhhHz,value.var="iid")
data_UaUnOdpg<-dcast(b_indiv_train,id~UaUnOdpg,value.var="iid")
data_QIQcRKCg<-dcast(b_indiv_train,id~QIQcRKCg,value.var="iid")
data_yNHqwYaJ<-dcast(b_indiv_train,id~yNHqwYaJ,value.var="iid")
data_rWlPNhUy<-dcast(b_indiv_train,id~rWlPNhUy,value.var="iid")
data_QcuPNLAv<-dcast(b_indiv_train,id~QcuPNLAv,value.var="iid")
data_nkxrhykC<-dcast(b_indiv_train,id~nkxrhykC,value.var="iid")
data_zTEEwTzG<-dcast(b_indiv_train,id~zTEEwTzG,value.var="iid")
data_NMsLrKWd<-dcast(b_indiv_train,id~NMsLrKWd,value.var="iid")
data_iHCKmQSy<-dcast(b_indiv_train,id~iHCKmQSy,value.var="iid")
data_UPswDJlm<-dcast(b_indiv_train,id~UPswDJlm,value.var="iid")
data_OhKTEjVy<-dcast(b_indiv_train,id~OhKTEjVy,value.var="iid")
data_jRXAvmTH<-dcast(b_indiv_train,id~jRXAvmTH,value.var="iid")
data_FHoVOXib<-dcast(b_indiv_train,id~FHoVOXib,value.var="iid")
data_OATvAQNG<-dcast(b_indiv_train,id~OATvAQNG,value.var="iid")
data_teSzyTms<-dcast(b_indiv_train,id~teSzyTms,value.var="iid")
data_FsUFnmgF<-dcast(b_indiv_train,id~FsUFnmgF,value.var="iid")
data_uDVGRBVU<-dcast(b_indiv_train,id~uDVGRBVU,value.var="iid")
data_WCMouTCp<-dcast(b_indiv_train,id~WCMouTCp,value.var="iid")
data_VKUGzaxx<-dcast(b_indiv_train,id~VKUGzaxx,value.var="iid")
data_tkFVflRJ<-dcast(b_indiv_train,id~tkFVflRJ,value.var="iid")
data_qhffLQpJ<-dcast(b_indiv_train,id~qhffLQpJ,value.var="iid")
data_dFaxStnz<-dcast(b_indiv_train,id~dFaxStnz,value.var="iid")
data_EzGVhUlW<-dcast(b_indiv_train,id~EzGVhUlW,value.var="iid")
data_pDeMFniB<-dcast(b_indiv_train,id~pDeMFniB,value.var="iid")
data_AxEjAWSE<-dcast(b_indiv_train,id~AxEjAWSE,value.var="iid")
data_MhvfpnqH<-dcast(b_indiv_train,id~MhvfpnqH,value.var="iid")
data_jdYXWZgD<-dcast(b_indiv_train,id~jdYXWZgD,value.var="iid")
data_LLZtRxnK<-dcast(b_indiv_train,id~LLZtRxnK,value.var="iid")
data_CtIAiLwz<-dcast(b_indiv_train,id~CtIAiLwz,value.var="iid")
data_NPNqQdIn<-dcast(b_indiv_train,id~NPNqQdIn,value.var="iid")
data_qzOZZsuS<-dcast(b_indiv_train,id~qzOZZsuS,value.var="iid")
data_vquBDhol<-dcast(b_indiv_train,id~vquBDhol,value.var="iid")
data_MMWrfMBi<-dcast(b_indiv_train,id~MMWrfMBi,value.var="iid")
data_GshWgURK<-dcast(b_indiv_train,id~GshWgURK,value.var="iid")
data_LSpCPhcU<-dcast(b_indiv_train,id~LSpCPhcU,value.var="iid")
data_pHYVhLJD<-dcast(b_indiv_train,id~pHYVhLJD,value.var="iid")
data_NocVJZYG<-dcast(b_indiv_train,id~NocVJZYG,value.var="iid")
data_zhbhQewN<-dcast(b_indiv_train,id~zhbhQewN,value.var="iid")
data_qxVAoxyX<-dcast(b_indiv_train,id~qxVAoxyX,value.var="iid")
data_sWADnjxA<-dcast(b_indiv_train,id~sWADnjxA,value.var="iid")
data_zgJdRdgg<-dcast(b_indiv_train,id~zgJdRdgg,value.var="iid")
data_rxwugNti<-dcast(b_indiv_train,id~rxwugNti,value.var="iid")
data_XIHNcHXI<-dcast(b_indiv_train,id~XIHNcHXI,value.var="iid")
data_tugScLvF<-dcast(b_indiv_train,id~tugScLvF,value.var="iid")
data_xTZOLcSX<-dcast(b_indiv_train,id~xTZOLcSX,value.var="iid")
data_eWNUvdjK<-dcast(b_indiv_train,id~eWNUvdjK,value.var="iid")
data_yxQmKfsS<-dcast(b_indiv_train,id~yxQmKfsS,value.var="iid")
data_PyTDmsQl<-dcast(b_indiv_train,id~PyTDmsQl,value.var="iid")
data_CnQHDRVZ<-dcast(b_indiv_train,id~CnQHDRVZ,value.var="iid")
data_VxXEkbdS<-dcast(b_indiv_train,id~VxXEkbdS,value.var="iid")
data_vVyGhGoB<-dcast(b_indiv_train,id~vVyGhGoB,value.var="iid")
data_qRplnnEM<-dcast(b_indiv_train,id~qRplnnEM,value.var="iid")
data_SCLDdPrm<-dcast(b_indiv_train,id~SCLDdPrm,value.var="iid")
data_HcutWGCs<-dcast(b_indiv_train,id~HcutWGCs,value.var="iid")
data_GlkLFREL<-dcast(b_indiv_train,id~GlkLFREL,value.var="iid")
data_NAZxDkiV<-dcast(b_indiv_train,id~NAZxDkiV,value.var="iid")
data_yjAfWuLb<-dcast(b_indiv_train,id~yjAfWuLb,value.var="iid")
data_GlktDEEv<-dcast(b_indiv_train,id~GlktDEEv,value.var="iid")
data_IIvMcTrH<-dcast(b_indiv_train,id~IIvMcTrH,value.var="iid")
data_JbDBFPPd<-dcast(b_indiv_train,id~JbDBFPPd,value.var="iid")
data_clCRDApV<-dcast(b_indiv_train,id~clCRDApV,value.var="iid")
data_aYGuxgyP<-dcast(b_indiv_train,id~aYGuxgyP,value.var="iid")
data_NZYkmhkD<-dcast(b_indiv_train,id~NZYkmhkD,value.var="iid")
data_fxWioPPP<-dcast(b_indiv_train,id~fxWioPPP,value.var="iid")
data_DWmTWcUm<-dcast(b_indiv_train,id~DWmTWcUm,value.var="iid")
data_PxgyaWYq<-dcast(b_indiv_train,id~PxgyaWYq,value.var="iid")
data_cavdrXpj<-dcast(b_indiv_train,id~cavdrXpj,value.var="iid")


data_BoxViLPz<-aggregate(BoxViLPz~id,b_indiv_train,sum)
data_qlLzyqpP<-aggregate(qlLzyqpP~id,b_indiv_train,sum)
data_unRAgFtX<-aggregate(unRAgFtX~id,b_indiv_train,sum)
data_TJGiunYp<-aggregate(TJGiunYp~id,b_indiv_train,sum)
data_WmKLEUcd<-aggregate(WmKLEUcd~id,b_indiv_train,sum)
data_DYgxQeEi<-aggregate(DYgxQeEi~id,b_indiv_train,sum)
data_jfsTwowc<-aggregate(jfsTwowc~id,b_indiv_train,sum)
data_MGfpfHam<-aggregate(MGfpfHam~id,b_indiv_train,sum)
data_esHWAAyG<-aggregate(esHWAAyG~id,b_indiv_train,sum)
data_DtcKwIEv<-aggregate(DtcKwIEv~id,b_indiv_train,sum)
data_ETgxnJOM<-aggregate(ETgxnJOM~id,b_indiv_train,sum)
data_gKsBCLMY<-aggregate(gKsBCLMY~id,b_indiv_train,sum)
data_TZDgOhYY<-aggregate(TZDgOhYY~id,b_indiv_train,sum)
data_sWElQwuC<-aggregate(sWElQwuC~id,b_indiv_train,sum)
data_jzBRbsEG<-aggregate(jzBRbsEG~id,b_indiv_train,sum)
data_CLTXEwmz<-aggregate(CLTXEwmz~id,b_indiv_train,sum)
data_WqEZQuJP<-aggregate(WqEZQuJP~id,b_indiv_train,sum)
data_dnmwvCng<-aggregate(dnmwvCng~id,b_indiv_train,sum)
data_DSttkpSI<-aggregate(DSttkpSI~id,b_indiv_train,sum)
data_sIiSADFG<-aggregate(sIiSADFG~id,b_indiv_train,sum)
data_uDmhgsaQ<-aggregate(uDmhgsaQ~id,b_indiv_train,sum)
data_hdDTwJhQ<-aggregate(hdDTwJhQ~id,b_indiv_train,sum)
data_AJgudnHB<-aggregate(AJgudnHB~id,b_indiv_train,sum)
data_iZhWxnWa<-aggregate(iZhWxnWa~id,b_indiv_train,sum)
data_fyfDnyQk<-aggregate(fyfDnyQk~id,b_indiv_train,sum)
data_wJthinfa<-aggregate(wJthinfa~id,b_indiv_train,sum)
data_nxAFXxLQ<-aggregate(nxAFXxLQ~id,b_indiv_train,sum)
data_mAeaImix<-aggregate(mAeaImix~id,b_indiv_train,sum)
data_HZqPmvkr<-aggregate(HZqPmvkr~id,b_indiv_train,sum)
data_ulQCDoYe<-aggregate(ulQCDoYe~id,b_indiv_train,sum)
data_tzYvQeOb<-aggregate(tzYvQeOb~id,b_indiv_train,sum)
data_NfpXxGQk<-aggregate(NfpXxGQk~id,b_indiv_train,sum)












b_hhold_train<-merge(b_hhold_train,data_HeUgMnzF,by="id");rm(data_HeUgMnzF)
b_hhold_train<-merge(b_hhold_train,data_CaukPfUC,by="id");rm(data_CaukPfUC)
b_hhold_train<-merge(b_hhold_train,data_MzEtIdUF,by="id");rm(data_MzEtIdUF)
b_hhold_train<-merge(b_hhold_train,data_gtnNTNam,by="id");rm(data_gtnNTNam)
b_hhold_train<-merge(b_hhold_train,data_SWoXNmPc,by="id");rm(data_SWoXNmPc)
b_hhold_train<-merge(b_hhold_train,data_eXbOkwhI,by="id");rm(data_eXbOkwhI)
b_hhold_train<-merge(b_hhold_train,data_OdXpbPGJ,by="id");rm(data_OdXpbPGJ)
b_hhold_train<-merge(b_hhold_train,data_XONDGWjH,by="id");rm(data_XONDGWjH)
b_hhold_train<-merge(b_hhold_train,data_KsFoQcUV,by="id");rm(data_KsFoQcUV)
b_hhold_train<-merge(b_hhold_train,data_qYRZCuJD,by="id");rm(data_qYRZCuJD)
b_hhold_train<-merge(b_hhold_train,data_FPQrjGnS,by="id");rm(data_FPQrjGnS)
b_hhold_train<-merge(b_hhold_train,data_hOamrctW,by="id");rm(data_hOamrctW)
b_hhold_train<-merge(b_hhold_train,data_XacGrSou,by="id");rm(data_XacGrSou)
b_hhold_train<-merge(b_hhold_train,data_UsmeXdIS,by="id");rm(data_UsmeXdIS)
b_hhold_train<-merge(b_hhold_train,data_igHwZsYz,by="id");rm(data_igHwZsYz)
b_hhold_train<-merge(b_hhold_train,data_cxWuAOZv,by="id");rm(data_cxWuAOZv)
b_hhold_train<-merge(b_hhold_train,data_AQpdiRUz,by="id");rm(data_AQpdiRUz)
b_hhold_train<-merge(b_hhold_train,data_AoLwmlEH,by="id");rm(data_AoLwmlEH)
b_hhold_train<-merge(b_hhold_train,data_nLUXHpZr,by="id");rm(data_nLUXHpZr)
b_hhold_train<-merge(b_hhold_train,data_CRLlSiFu,by="id");rm(data_CRLlSiFu)
b_hhold_train<-merge(b_hhold_train,data_jYpOAjPW,by="id");rm(data_jYpOAjPW)
b_hhold_train<-merge(b_hhold_train,data_NAxEQZVi,by="id");rm(data_NAxEQZVi)
b_hhold_train<-merge(b_hhold_train,data_QvgxCmCV,by="id");rm(data_QvgxCmCV)
b_hhold_train<-merge(b_hhold_train,data_kvMGuSDN,by="id");rm(data_kvMGuSDN)
b_hhold_train<-merge(b_hhold_train,data_AjYsrafY,by="id");rm(data_AjYsrafY)
b_hhold_train<-merge(b_hhold_train,data_GNaMafZC,by="id");rm(data_GNaMafZC)
b_hhold_train<-merge(b_hhold_train,data_zTLPJYTw,by="id");rm(data_zTLPJYTw)
b_hhold_train<-merge(b_hhold_train,data_QKzxTGus,by="id");rm(data_QKzxTGus)
b_hhold_train<-merge(b_hhold_train,data_SGeOiUlZ,by="id");rm(data_SGeOiUlZ)
b_hhold_train<-merge(b_hhold_train,data_MUrHEJeh,by="id");rm(data_MUrHEJeh)
b_hhold_train<-merge(b_hhold_train,data_XBldkztv,by="id");rm(data_XBldkztv)
b_hhold_train<-merge(b_hhold_train,data_tbgZsPXD,by="id");rm(data_tbgZsPXD)
b_hhold_train<-merge(b_hhold_train,data_ukWqmeSS,by="id");rm(data_ukWqmeSS)
b_hhold_train<-merge(b_hhold_train,data_qqVibbSA,by="id");rm(data_qqVibbSA)
b_hhold_train<-merge(b_hhold_train,data_MgCoFhXK,by="id");rm(data_MgCoFhXK)
b_hhold_train<-merge(b_hhold_train,data_rFpoTXAq,by="id");rm(data_rFpoTXAq)
b_hhold_train<-merge(b_hhold_train,data_RXcLsVAQ,by="id");rm(data_RXcLsVAQ)
b_hhold_train<-merge(b_hhold_train,data_rQWIpTiG,by="id");rm(data_rQWIpTiG)
b_hhold_train<-merge(b_hhold_train,data_XizJGmbu,by="id");rm(data_XizJGmbu)
b_hhold_train<-merge(b_hhold_train,data_xqUooaNJ,by="id");rm(data_xqUooaNJ)

a_train<-b_hhold_train

a_train_cat<-sapply(a_train, is.factor)
a_train_cat<-a_train[,a_train_cat]
a_train_con<-sapply(a_train, is.numeric)
a_train_con<-a_train[,a_train_con]
y<-data.frame(poor=a_train$poor)
a_train_dum<-dummy.data.frame(a_train_cat[-157])
a_train_com<-cbind(a_train_con,a_train_dum,y)


nearZeroVar(a_train_com[-c(1,1133)])


if (length(nearZeroVar(a_train_com[-c(1,1133)])) > 0) {
  a_train_com <- a_train_com[, -nearZeroVar(a_train_com)] 
}


a_hhold_test<-read.csv('A_hhold_test.csv')
a_indiv_test<-read.csv('A_indiv_test.csv')


data_HeUgMnzF <- dcast(a_indiv_test , id ~ HeUgMnzF , value.var="iid")
data_CaukPfUC <- dcast(a_indiv_test , id ~ CaukPfUC , value.var="iid")
data_MzEtIdUF <- dcast(a_indiv_test , id ~ MzEtIdUF , value.var="iid")
data_gtnNTNam <- dcast(a_indiv_test , id ~ gtnNTNam , value.var="iid")
data_SWoXNmPc <- dcast(a_indiv_test , id ~ SWoXNmPc , value.var="iid")
data_eXbOkwhI <- dcast(a_indiv_test , id ~ eXbOkwhI , value.var="iid")
#data_OdXpbPGJ <- dcast(a_indiv_test , id ~ OdXpbPGJ , value.var="iid")
data_OdXpbPGJ<-aggregate(OdXpbPGJ~id,a_indiv_test,sum)
data_XONDGWjH <- dcast(a_indiv_test , id ~ XONDGWjH , value.var="iid")
data_KsFoQcUV <- dcast(a_indiv_test , id ~ KsFoQcUV , value.var="iid")
data_qYRZCuJD <- dcast(a_indiv_test , id ~ qYRZCuJD , value.var="iid")
data_FPQrjGnS <- dcast(a_indiv_test , id ~ FPQrjGnS , value.var="iid")
data_hOamrctW <- dcast(a_indiv_test , id ~ hOamrctW , value.var="iid")
data_XacGrSou <- dcast(a_indiv_test , id ~ XacGrSou , value.var="iid")
data_UsmeXdIS <- dcast(a_indiv_test , id ~ UsmeXdIS , value.var="iid")
data_igHwZsYz <- dcast(a_indiv_test , id ~ igHwZsYz , value.var="iid")
data_cxWuAOZv <- dcast(a_indiv_test , id ~ cxWuAOZv , value.var="iid")
data_AQpdiRUz <- dcast(a_indiv_test , id ~ AQpdiRUz , value.var="iid")
data_AoLwmlEH <- dcast(a_indiv_test , id ~ AoLwmlEH , value.var="iid")
data_nLUXHpZr <- dcast(a_indiv_test , id ~ nLUXHpZr , value.var="iid")
data_CRLlSiFu <- dcast(a_indiv_test , id ~ CRLlSiFu , value.var="iid")
data_jYpOAjPW <- dcast(a_indiv_test , id ~ jYpOAjPW , value.var="iid")
data_NAxEQZVi <- dcast(a_indiv_test , id ~ NAxEQZVi , value.var="iid")
data_QvgxCmCV <- dcast(a_indiv_test , id ~ QvgxCmCV , value.var="iid")
data_kvMGuSDN <- dcast(a_indiv_test , id ~ kvMGuSDN , value.var="iid")
data_AjYsrafY <- dcast(a_indiv_test , id ~ AjYsrafY , value.var="iid")
data_GNaMafZC <- dcast(a_indiv_test , id ~ GNaMafZC , value.var="iid")
data_zTLPJYTw <- dcast(a_indiv_test , id ~ zTLPJYTw , value.var="iid")
data_QKzxTGus <- dcast(a_indiv_test , id ~ QKzxTGus , value.var="iid")
data_SGeOiUlZ <- dcast(a_indiv_test , id ~ SGeOiUlZ , value.var="iid")
data_MUrHEJeh <- dcast(a_indiv_test , id ~ MUrHEJeh , value.var="iid")
data_XBldkztv <- dcast(a_indiv_test , id ~ XBldkztv , value.var="iid")
data_tbgZsPXD <- dcast(a_indiv_test , id ~ tbgZsPXD , value.var="iid")
#data_ukWqmeSS <- dcast(a_indiv_test , id ~ ukWqmeSS , value.var="iid")
data_ukWqmeSS<-aggregate(ukWqmeSS~id,a_indiv_test,sum)
data_qqVibbSA <- dcast(a_indiv_test , id ~ qqVibbSA , value.var="iid")
data_MgCoFhXK <- dcast(a_indiv_test , id ~ MgCoFhXK , value.var="iid")
data_rFpoTXAq <- dcast(a_indiv_test , id ~ rFpoTXAq , value.var="iid")
data_RXcLsVAQ <- dcast(a_indiv_test , id ~ RXcLsVAQ , value.var="iid")
data_rQWIpTiG <- dcast(a_indiv_test , id ~ rQWIpTiG , value.var="iid")
data_XizJGmbu <- dcast(a_indiv_test , id ~ XizJGmbu , value.var="iid")
data_xqUooaNJ <- dcast(a_indiv_test , id ~ xqUooaNJ , value.var="iid")

a_hhold_test<-merge(a_hhold_test,data_HeUgMnzF,by="id");rm(data_HeUgMnzF)
a_hhold_test<-merge(a_hhold_test,data_CaukPfUC,by="id");rm(data_CaukPfUC)
a_hhold_test<-merge(a_hhold_test,data_MzEtIdUF,by="id");rm(data_MzEtIdUF)
a_hhold_test<-merge(a_hhold_test,data_gtnNTNam,by="id");rm(data_gtnNTNam)
a_hhold_test<-merge(a_hhold_test,data_SWoXNmPc,by="id");rm(data_SWoXNmPc)
a_hhold_test<-merge(a_hhold_test,data_eXbOkwhI,by="id");rm(data_eXbOkwhI)
a_hhold_test<-merge(a_hhold_test,data_OdXpbPGJ,by="id");rm(data_OdXpbPGJ)
a_hhold_test<-merge(a_hhold_test,data_XONDGWjH,by="id");rm(data_XONDGWjH)
a_hhold_test<-merge(a_hhold_test,data_KsFoQcUV,by="id");rm(data_KsFoQcUV)
a_hhold_test<-merge(a_hhold_test,data_qYRZCuJD,by="id");rm(data_qYRZCuJD)
a_hhold_test<-merge(a_hhold_test,data_FPQrjGnS,by="id");rm(data_FPQrjGnS)
a_hhold_test<-merge(a_hhold_test,data_hOamrctW,by="id");rm(data_hOamrctW)
a_hhold_test<-merge(a_hhold_test,data_XacGrSou,by="id");rm(data_XacGrSou)
a_hhold_test<-merge(a_hhold_test,data_UsmeXdIS,by="id");rm(data_UsmeXdIS)
a_hhold_test<-merge(a_hhold_test,data_igHwZsYz,by="id");rm(data_igHwZsYz)
a_hhold_test<-merge(a_hhold_test,data_cxWuAOZv,by="id");rm(data_cxWuAOZv)
a_hhold_test<-merge(a_hhold_test,data_AQpdiRUz,by="id");rm(data_AQpdiRUz)
a_hhold_test<-merge(a_hhold_test,data_AoLwmlEH,by="id");rm(data_AoLwmlEH)
a_hhold_test<-merge(a_hhold_test,data_nLUXHpZr,by="id");rm(data_nLUXHpZr)
a_hhold_test<-merge(a_hhold_test,data_CRLlSiFu,by="id");rm(data_CRLlSiFu)
a_hhold_test<-merge(a_hhold_test,data_jYpOAjPW,by="id");rm(data_jYpOAjPW)
a_hhold_test<-merge(a_hhold_test,data_NAxEQZVi,by="id");rm(data_NAxEQZVi)
a_hhold_test<-merge(a_hhold_test,data_QvgxCmCV,by="id");rm(data_QvgxCmCV)
a_hhold_test<-merge(a_hhold_test,data_kvMGuSDN,by="id");rm(data_kvMGuSDN)
a_hhold_test<-merge(a_hhold_test,data_AjYsrafY,by="id");rm(data_AjYsrafY)
a_hhold_test<-merge(a_hhold_test,data_GNaMafZC,by="id");rm(data_GNaMafZC)
a_hhold_test<-merge(a_hhold_test,data_zTLPJYTw,by="id");rm(data_zTLPJYTw)
a_hhold_test<-merge(a_hhold_test,data_QKzxTGus,by="id");rm(data_QKzxTGus)
a_hhold_test<-merge(a_hhold_test,data_SGeOiUlZ,by="id");rm(data_SGeOiUlZ)
a_hhold_test<-merge(a_hhold_test,data_MUrHEJeh,by="id");rm(data_MUrHEJeh)
a_hhold_test<-merge(a_hhold_test,data_XBldkztv,by="id");rm(data_XBldkztv)
a_hhold_test<-merge(a_hhold_test,data_tbgZsPXD,by="id");rm(data_tbgZsPXD)
a_hhold_test<-merge(a_hhold_test,data_ukWqmeSS,by="id");rm(data_ukWqmeSS)
a_hhold_test<-merge(a_hhold_test,data_qqVibbSA,by="id");rm(data_qqVibbSA)
a_hhold_test<-merge(a_hhold_test,data_MgCoFhXK,by="id");rm(data_MgCoFhXK)
a_hhold_test<-merge(a_hhold_test,data_rFpoTXAq,by="id");rm(data_rFpoTXAq)
a_hhold_test<-merge(a_hhold_test,data_RXcLsVAQ,by="id");rm(data_RXcLsVAQ)
a_hhold_test<-merge(a_hhold_test,data_rQWIpTiG,by="id");rm(data_rQWIpTiG)
a_hhold_test<-merge(a_hhold_test,data_XizJGmbu,by="id");rm(data_XizJGmbu)
a_hhold_test<-merge(a_hhold_test,data_xqUooaNJ,by="id");rm(data_xqUooaNJ)


a_test<-a_hhold_test

a_test_cat<-sapply(a_test, is.factor)
a_test_cat<-a_test[,a_test_cat]
a_test_con<-sapply(a_test, is.numeric)
a_test_con<-a_test[,a_test_con]

a_test_dum<-dummy.data.frame(a_test_cat)
a_test_com<-cbind(a_test_con,a_test_dum)


# RandomForest Model building ----------------------------------------------------------
set.seed(1234)
fit <- randomForest(as.factor(poor) ~ ., data=a_train_com[-1],keep.forest=TRUE ,importance=TRUE,ntree=200)
#varImpPlot(fit)
pred <- predict(fit,a_train_com,type="prob")
MultiLogLoss(pred,a_train_com$poor)
