library(reshape2)

b_hhold_train<-read.csv('B_hhold_train.csv')
b_indiv_train<-read.csv('B_indiv_train.csv')

#write.csv(names(b_indiv_train),'b_names.csv',row.names = F)
#lapply(b_indiv_train, class)
#write.csv(lapply(b_indiv_train, class),'b1_names.csv',row.names = F)
data_MmKGUOrD<-dcast(b_indiv_train,id~MmKGUOrD,value.var="iid")
data_splgBZfe<-dcast(b_indiv_train,id~splgBZfe,value.var="iid")
data_JTCCBpjX<-dcast(b_indiv_train,id~JTCCBpjX,value.var="iid")
data_akGaJaYF<-dcast(b_indiv_train,id~akGaJaYF,value.var="iid")
data_eYoMkEyN<-dcast(b_indiv_train,id~eYoMkEyN,value.var="iid")
data_bmhTgzYu<-dcast(b_indiv_train,id~bmhTgzYu,value.var="iid")
data_GjxOmHgp<-dcast(b_indiv_train,id~GjxOmHgp,value.var="iid")
data_mYMBWfIH<-dcast(b_indiv_train,id~mYMBWfIH,value.var="iid")
data_SZucUQmM<-dcast(b_indiv_train,id~SZucUQmM,value.var="iid")
data_EfqFGRSF<-dcast(b_indiv_train,id~EfqFGRSF,value.var="iid")
data_plDSQDzp<-dcast(b_indiv_train,id~plDSQDzp,value.var="iid")
data_jyZvBZlo<-dcast(b_indiv_train,id~jyZvBZlo,value.var="iid")
data_gyxBUEPe<-dcast(b_indiv_train,id~gyxBUEPe,value.var="iid")
data_lTdxcpBA<-dcast(b_indiv_train,id~lTdxcpBA,value.var="iid")
data_yoijDqAm<-dcast(b_indiv_train,id~yoijDqAm,value.var="iid")
data_LkhgHzsx<-dcast(b_indiv_train,id~LkhgHzsx,value.var="iid")
data_UUYXAsfo<-dcast(b_indiv_train,id~UUYXAsfo,value.var="iid")
data_IPBrAaYt<-dcast(b_indiv_train,id~IPBrAaYt,value.var="iid")
data_hCgDHGEc<-dcast(b_indiv_train,id~hCgDHGEc,value.var="iid")
data_GFXSuQvB<-dcast(b_indiv_train,id~GFXSuQvB,value.var="iid")
data_UPtsFglH<-dcast(b_indiv_train,id~UPtsFglH,value.var="iid")
data_HZEsXrsF<-dcast(b_indiv_train,id~HZEsXrsF,value.var="iid")
data_kgVoFHRj<-dcast(b_indiv_train,id~kgVoFHRj,value.var="iid")
data_pqbNHKuK<-dcast(b_indiv_train,id~pqbNHKuK,value.var="iid")
data_gEqzZWXR<-dcast(b_indiv_train,id~gEqzZWXR,value.var="iid")
data_UkXhNUcd<-dcast(b_indiv_train,id~UkXhNUcd,value.var="iid")
data_hggXZmdr<-dcast(b_indiv_train,id~hggXZmdr,value.var="iid")
data_uyhBLPFL<-dcast(b_indiv_train,id~uyhBLPFL,value.var="iid")
data_hwJpBxAl<-dcast(b_indiv_train,id~hwJpBxAl,value.var="iid")
data_BXZfamTt<-dcast(b_indiv_train,id~BXZfamTt,value.var="iid")
data_jkutpUMt<-dcast(b_indiv_train,id~jkutpUMt,value.var="iid")
data_lFkBekuJ<-dcast(b_indiv_train,id~lFkBekuJ,value.var="iid")
data_aTEyAdSs<-dcast(b_indiv_train,id~aTEyAdSs,value.var="iid")
data_TdfmGIAn<-dcast(b_indiv_train,id~TdfmGIAn,value.var="iid")
data_kaVnoUbJ<-dcast(b_indiv_train,id~kaVnoUbJ,value.var="iid")
data_bngqQTHD<-dcast(b_indiv_train,id~bngqQTHD,value.var="iid")
data_cRQWeYKZ<-dcast(b_indiv_train,id~cRQWeYKZ,value.var="iid")
data_ErqgHOEp<-dcast(b_indiv_train,id~ErqgHOEp,value.var="iid")
data_Ftzawcsw<-dcast(b_indiv_train,id~Ftzawcsw,value.var="iid")
data_SlqMdbUr<-dcast(b_indiv_train,id~SlqMdbUr,value.var="iid")
data_jyLFRgZs<-dcast(b_indiv_train,id~jyLFRgZs,value.var="iid")
data_TsredPtf<-dcast(b_indiv_train,id~TsredPtf,value.var="iid")
data_pFOEMbYu<-dcast(b_indiv_train,id~pFOEMbYu,value.var="iid")
data_nOoTxqCQ<-dcast(b_indiv_train,id~nOoTxqCQ,value.var="iid")
data_xohFWnds<-dcast(b_indiv_train,id~xohFWnds,value.var="iid")
data_JYKPCImt<-dcast(b_indiv_train,id~JYKPCImt,value.var="iid")
data_wEtnhPQs<-dcast(b_indiv_train,id~wEtnhPQs,value.var="iid")
data_LIoTrAzw<-dcast(b_indiv_train,id~LIoTrAzw,value.var="iid")
data_IoJgECCi<-dcast(b_indiv_train,id~IoJgECCi,value.var="iid")
data_YwcPaCNf<-dcast(b_indiv_train,id~YwcPaCNf,value.var="iid")
data_PgXpVWEU<-dcast(b_indiv_train,id~PgXpVWEU,value.var="iid")
data_ENQEzjVj<-dcast(b_indiv_train,id~ENQEzjVj,value.var="iid")
data_RFLvRzHv<-dcast(b_indiv_train,id~RFLvRzHv,value.var="iid")
data_xhqvDVIs<-dcast(b_indiv_train,id~xhqvDVIs,value.var="iid")
data_YhbMdUgd<-dcast(b_indiv_train,id~YhbMdUgd,value.var="iid")
data_cPHgLSMk<-dcast(b_indiv_train,id~cPHgLSMk,value.var="iid")
data_jBZoYONA<-dcast(b_indiv_train,id~jBZoYONA,value.var="iid")
data_HHbZiXXp<-dcast(b_indiv_train,id~HHbZiXXp,value.var="iid")
data_DsHJnzeZ<-dcast(b_indiv_train,id~DsHJnzeZ,value.var="iid")
data_PwxicsdL<-dcast(b_indiv_train,id~PwxicsdL,value.var="iid")
data_UZLkbGnz<-dcast(b_indiv_train,id~UZLkbGnz,value.var="iid")
data_xNhKVNgq<-dcast(b_indiv_train,id~xNhKVNgq,value.var="iid")
data_nIgKFReH<-dcast(b_indiv_train,id~nIgKFReH,value.var="iid")
data_FgnMveDS<-dcast(b_indiv_train,id~FgnMveDS,value.var="iid")
data_NdBZKehA<-dcast(b_indiv_train,id~NdBZKehA,value.var="iid")
data_mlyFwTHy<-dcast(b_indiv_train,id~mlyFwTHy,value.var="iid")
data_KjMhhJdX<-dcast(b_indiv_train,id~KjMhhJdX,value.var="iid")
data_zXonuRgn<-dcast(b_indiv_train,id~zXonuRgn,value.var="iid")
data_MWVlKQoo<-dcast(b_indiv_train,id~MWVlKQoo,value.var="iid")
data_mQezyEOr<-dcast(b_indiv_train,id~mQezyEOr,value.var="iid")
data_nPlbGBjS<-dcast(b_indiv_train,id~nPlbGBjS,value.var="iid")
data_nmrQVORl<-dcast(b_indiv_train,id~nmrQVORl,value.var="iid")
data_KGtdytLE<-dcast(b_indiv_train,id~KGtdytLE,value.var="iid")
data_DELHTNkd<-dcast(b_indiv_train,id~DELHTNkd,value.var="iid")
data_rZfVzfDA<-dcast(b_indiv_train,id~rZfVzfDA,value.var="iid")
data_ZHOSEFIu<-dcast(b_indiv_train,id~ZHOSEFIu,value.var="iid")
data_ogUWmSXZ<-dcast(b_indiv_train,id~ogUWmSXZ,value.var="iid")
data_VWMwzteg<-dcast(b_indiv_train,id~VWMwzteg,value.var="iid")
data_HaaXLOfY<-dcast(b_indiv_train,id~HaaXLOfY,value.var="iid")
data_NCyUzkfp<-dcast(b_indiv_train,id~NCyUzkfp,value.var="iid")
data_nAjgFRel<-dcast(b_indiv_train,id~nAjgFRel,value.var="iid")
data_XZUEzGLM<-dcast(b_indiv_train,id~XZUEzGLM,value.var="iid")
data_OFkIQOzS<-dcast(b_indiv_train,id~OFkIQOzS,value.var="iid")
data_BqXRUQgi<-dcast(b_indiv_train,id~BqXRUQgi,value.var="iid")
data_ywnHMkvq<-dcast(b_indiv_train,id~ywnHMkvq,value.var="iid")
data_eKkwQtwX<-dcast(b_indiv_train,id~eKkwQtwX,value.var="iid")
data_fwRLKHlN<-dcast(b_indiv_train,id~fwRLKHlN,value.var="iid")
data_jUwlkffQ<-dcast(b_indiv_train,id~jUwlkffQ,value.var="iid")
data_DAeoUuuN<-dcast(b_indiv_train,id~DAeoUuuN,value.var="iid")
data_gsofZtJJ<-dcast(b_indiv_train,id~gsofZtJJ,value.var="iid")
data_HQPtUibh<-dcast(b_indiv_train,id~HQPtUibh,value.var="iid")
data_aqYWloSo<-dcast(b_indiv_train,id~aqYWloSo,value.var="iid")
data_RUTkmJrl<-dcast(b_indiv_train,id~RUTkmJrl,value.var="iid")
data_tQzcGkNE<-dcast(b_indiv_train,id~tQzcGkNE,value.var="iid")
data_VszNwfYx<-dcast(b_indiv_train,id~VszNwfYx,value.var="iid")
data_hnwVYJyV<-dcast(b_indiv_train,id~hnwVYJyV,value.var="iid")
data_RsMBXisy<-dcast(b_indiv_train,id~RsMBXisy,value.var="iid")
data_MiGIkxpV<-dcast(b_indiv_train,id~MiGIkxpV,value.var="iid")
data_xbOnnZEV<-dcast(b_indiv_train,id~xbOnnZEV,value.var="iid")
data_cGaHwCJA<-dcast(b_indiv_train,id~cGaHwCJA,value.var="iid")
data_dfchpzYE<-dcast(b_indiv_train,id~dfchpzYE,value.var="iid")
data_fwBNLzWK<-dcast(b_indiv_train,id~fwBNLzWK,value.var="iid")
data_lLoRmWKX<-dcast(b_indiv_train,id~lLoRmWKX,value.var="iid")
data_GhzvKcjl<-dcast(b_indiv_train,id~GhzvKcjl,value.var="iid")
data_EpWsJmrF<-dcast(b_indiv_train,id~EpWsJmrF,value.var="iid")
data_wpoJgbis<-dcast(b_indiv_train,id~wpoJgbis,value.var="iid")
data_KyTRKtbW<-dcast(b_indiv_train,id~KyTRKtbW,value.var="iid")
data_xlJGUBXM<-dcast(b_indiv_train,id~xlJGUBXM,value.var="iid")
data_zuvYUDSL<-dcast(b_indiv_train,id~zuvYUDSL,value.var="iid")
data_ozvFfhhM<-dcast(b_indiv_train,id~ozvFfhhM,value.var="iid")
data_ljaNZowA<-dcast(b_indiv_train,id~ljaNZowA,value.var="iid")
data_sbjoLEKh<-dcast(b_indiv_train,id~sbjoLEKh,value.var="iid")
data_pyvZUOyi<-dcast(b_indiv_train,id~pyvZUOyi,value.var="iid")
data_FldbnriM<-dcast(b_indiv_train,id~FldbnriM,value.var="iid")
data_FyXQULwx<-dcast(b_indiv_train,id~FyXQULwx,value.var="iid")
data_UUYYcars<-dcast(b_indiv_train,id~UUYYcars,value.var="iid")
data_xMysunyA<-dcast(b_indiv_train,id~xMysunyA,value.var="iid")
data_FOIfEcny<-dcast(b_indiv_train,id~FOIfEcny,value.var="iid")
data_BhPvRtpj<-dcast(b_indiv_train,id~BhPvRtpj,value.var="iid")
data_JniMXoSr<-dcast(b_indiv_train,id~JniMXoSr,value.var="iid")
data_AFSIVjPG<-dcast(b_indiv_train,id~AFSIVjPG,value.var="iid")
data_lnMlvpes<-dcast(b_indiv_train,id~lnMlvpes,value.var="iid")
data_HrXGKbwr<-dcast(b_indiv_train,id~HrXGKbwr,value.var="iid")
data_NUefhhHz<-dcast(b_indiv_train,id~NUefhhHz,value.var="iid")
data_UaUnOdpg<-dcast(b_indiv_train,id~UaUnOdpg,value.var="iid")
data_QIQcRKCg<-dcast(b_indiv_train,id~QIQcRKCg,value.var="iid")
data_yNHqwYaJ<-dcast(b_indiv_train,id~yNHqwYaJ,value.var="iid")
data_rWlPNhUy<-dcast(b_indiv_train,id~rWlPNhUy,value.var="iid")
data_QcuPNLAv<-dcast(b_indiv_train,id~QcuPNLAv,value.var="iid")
data_nkxrhykC<-dcast(b_indiv_train,id~nkxrhykC,value.var="iid")
data_zTEEwTzG<-dcast(b_indiv_train,id~zTEEwTzG,value.var="iid")
data_NMsLrKWd<-dcast(b_indiv_train,id~NMsLrKWd,value.var="iid")
data_iHCKmQSy<-dcast(b_indiv_train,id~iHCKmQSy,value.var="iid")
data_UPswDJlm<-dcast(b_indiv_train,id~UPswDJlm,value.var="iid")
data_OhKTEjVy<-dcast(b_indiv_train,id~OhKTEjVy,value.var="iid")
data_jRXAvmTH<-dcast(b_indiv_train,id~jRXAvmTH,value.var="iid")
data_FHoVOXib<-dcast(b_indiv_train,id~FHoVOXib,value.var="iid")
data_OATvAQNG<-dcast(b_indiv_train,id~OATvAQNG,value.var="iid")
data_teSzyTms<-dcast(b_indiv_train,id~teSzyTms,value.var="iid")
data_FsUFnmgF<-dcast(b_indiv_train,id~FsUFnmgF,value.var="iid")
data_uDVGRBVU<-dcast(b_indiv_train,id~uDVGRBVU,value.var="iid")
data_WCMouTCp<-dcast(b_indiv_train,id~WCMouTCp,value.var="iid")
data_VKUGzaxx<-dcast(b_indiv_train,id~VKUGzaxx,value.var="iid")
data_tkFVflRJ<-dcast(b_indiv_train,id~tkFVflRJ,value.var="iid")
data_qhffLQpJ<-dcast(b_indiv_train,id~qhffLQpJ,value.var="iid")
data_dFaxStnz<-dcast(b_indiv_train,id~dFaxStnz,value.var="iid")
data_EzGVhUlW<-dcast(b_indiv_train,id~EzGVhUlW,value.var="iid")
data_pDeMFniB<-dcast(b_indiv_train,id~pDeMFniB,value.var="iid")
data_AxEjAWSE<-dcast(b_indiv_train,id~AxEjAWSE,value.var="iid")
data_MhvfpnqH<-dcast(b_indiv_train,id~MhvfpnqH,value.var="iid")
data_jdYXWZgD<-dcast(b_indiv_train,id~jdYXWZgD,value.var="iid")
data_LLZtRxnK<-dcast(b_indiv_train,id~LLZtRxnK,value.var="iid")
data_CtIAiLwz<-dcast(b_indiv_train,id~CtIAiLwz,value.var="iid")
data_NPNqQdIn<-dcast(b_indiv_train,id~NPNqQdIn,value.var="iid")
data_qzOZZsuS<-dcast(b_indiv_train,id~qzOZZsuS,value.var="iid")
data_vquBDhol<-dcast(b_indiv_train,id~vquBDhol,value.var="iid")
data_MMWrfMBi<-dcast(b_indiv_train,id~MMWrfMBi,value.var="iid")
data_GshWgURK<-dcast(b_indiv_train,id~GshWgURK,value.var="iid")
data_LSpCPhcU<-dcast(b_indiv_train,id~LSpCPhcU,value.var="iid")
data_pHYVhLJD<-dcast(b_indiv_train,id~pHYVhLJD,value.var="iid")
data_NocVJZYG<-dcast(b_indiv_train,id~NocVJZYG,value.var="iid")
data_zhbhQewN<-dcast(b_indiv_train,id~zhbhQewN,value.var="iid")
data_qxVAoxyX<-dcast(b_indiv_train,id~qxVAoxyX,value.var="iid")
data_sWADnjxA<-dcast(b_indiv_train,id~sWADnjxA,value.var="iid")
data_zgJdRdgg<-dcast(b_indiv_train,id~zgJdRdgg,value.var="iid")
data_rxwugNti<-dcast(b_indiv_train,id~rxwugNti,value.var="iid")
data_XIHNcHXI<-dcast(b_indiv_train,id~XIHNcHXI,value.var="iid")
data_tugScLvF<-dcast(b_indiv_train,id~tugScLvF,value.var="iid")
data_xTZOLcSX<-dcast(b_indiv_train,id~xTZOLcSX,value.var="iid")
data_eWNUvdjK<-dcast(b_indiv_train,id~eWNUvdjK,value.var="iid")
data_yxQmKfsS<-dcast(b_indiv_train,id~yxQmKfsS,value.var="iid")
data_PyTDmsQl<-dcast(b_indiv_train,id~PyTDmsQl,value.var="iid")
data_CnQHDRVZ<-dcast(b_indiv_train,id~CnQHDRVZ,value.var="iid")
data_VxXEkbdS<-dcast(b_indiv_train,id~VxXEkbdS,value.var="iid")
data_vVyGhGoB<-dcast(b_indiv_train,id~vVyGhGoB,value.var="iid")
data_qRplnnEM<-dcast(b_indiv_train,id~qRplnnEM,value.var="iid")
data_SCLDdPrm<-dcast(b_indiv_train,id~SCLDdPrm,value.var="iid")
data_HcutWGCs<-dcast(b_indiv_train,id~HcutWGCs,value.var="iid")
data_GlkLFREL<-dcast(b_indiv_train,id~GlkLFREL,value.var="iid")
data_NAZxDkiV<-dcast(b_indiv_train,id~NAZxDkiV,value.var="iid")
data_yjAfWuLb<-dcast(b_indiv_train,id~yjAfWuLb,value.var="iid")
data_GlktDEEv<-dcast(b_indiv_train,id~GlktDEEv,value.var="iid")
data_IIvMcTrH<-dcast(b_indiv_train,id~IIvMcTrH,value.var="iid")
data_JbDBFPPd<-dcast(b_indiv_train,id~JbDBFPPd,value.var="iid")
data_clCRDApV<-dcast(b_indiv_train,id~clCRDApV,value.var="iid")
data_aYGuxgyP<-dcast(b_indiv_train,id~aYGuxgyP,value.var="iid")
data_NZYkmhkD<-dcast(b_indiv_train,id~NZYkmhkD,value.var="iid")
data_fxWioPPP<-dcast(b_indiv_train,id~fxWioPPP,value.var="iid")
data_DWmTWcUm<-dcast(b_indiv_train,id~DWmTWcUm,value.var="iid")
data_PxgyaWYq<-dcast(b_indiv_train,id~PxgyaWYq,value.var="iid")
data_cavdrXpj<-dcast(b_indiv_train,id~cavdrXpj,value.var="iid")


b_hhold_train<-merge(b_hhold_train,data_MmKGUOrD,by="id");rm(data_MmKGUOrD)
b_hhold_train<-merge(b_hhold_train,data_splgBZfe,by="id");rm(data_splgBZfe)
b_hhold_train<-merge(b_hhold_train,data_JTCCBpjX,by="id");rm(data_JTCCBpjX)
b_hhold_train<-merge(b_hhold_train,data_akGaJaYF,by="id");rm(data_akGaJaYF)
b_hhold_train<-merge(b_hhold_train,data_eYoMkEyN,by="id");rm(data_eYoMkEyN)
b_hhold_train<-merge(b_hhold_train,data_bmhTgzYu,by="id");rm(data_bmhTgzYu)
b_hhold_train<-merge(b_hhold_train,data_GjxOmHgp,by="id");rm(data_GjxOmHgp)
b_hhold_train<-merge(b_hhold_train,data_mYMBWfIH,by="id");rm(data_mYMBWfIH)
b_hhold_train<-merge(b_hhold_train,data_SZucUQmM,by="id");rm(data_SZucUQmM)
b_hhold_train<-merge(b_hhold_train,data_EfqFGRSF,by="id");rm(data_EfqFGRSF)
b_hhold_train<-merge(b_hhold_train,data_plDSQDzp,by="id");rm(data_plDSQDzp)
b_hhold_train<-merge(b_hhold_train,data_jyZvBZlo,by="id");rm(data_jyZvBZlo)
b_hhold_train<-merge(b_hhold_train,data_gyxBUEPe,by="id");rm(data_gyxBUEPe)
b_hhold_train<-merge(b_hhold_train,data_lTdxcpBA,by="id");rm(data_lTdxcpBA)
b_hhold_train<-merge(b_hhold_train,data_yoijDqAm,by="id");rm(data_yoijDqAm)
b_hhold_train<-merge(b_hhold_train,data_LkhgHzsx,by="id");rm(data_LkhgHzsx)
b_hhold_train<-merge(b_hhold_train,data_UUYXAsfo,by="id");rm(data_UUYXAsfo)
b_hhold_train<-merge(b_hhold_train,data_IPBrAaYt,by="id");rm(data_IPBrAaYt)
b_hhold_train<-merge(b_hhold_train,data_hCgDHGEc,by="id");rm(data_hCgDHGEc)
b_hhold_train<-merge(b_hhold_train,data_GFXSuQvB,by="id");rm(data_GFXSuQvB)
b_hhold_train<-merge(b_hhold_train,data_UPtsFglH,by="id");rm(data_UPtsFglH)
b_hhold_train<-merge(b_hhold_train,data_HZEsXrsF,by="id");rm(data_HZEsXrsF)
b_hhold_train<-merge(b_hhold_train,data_kgVoFHRj,by="id");rm(data_kgVoFHRj)
b_hhold_train<-merge(b_hhold_train,data_pqbNHKuK,by="id");rm(data_pqbNHKuK)
b_hhold_train<-merge(b_hhold_train,data_gEqzZWXR,by="id");rm(data_gEqzZWXR)
b_hhold_train<-merge(b_hhold_train,data_UkXhNUcd,by="id");rm(data_UkXhNUcd)
b_hhold_train<-merge(b_hhold_train,data_hggXZmdr,by="id");rm(data_hggXZmdr)
b_hhold_train<-merge(b_hhold_train,data_uyhBLPFL,by="id");rm(data_uyhBLPFL)
b_hhold_train<-merge(b_hhold_train,data_hwJpBxAl,by="id");rm(data_hwJpBxAl)
b_hhold_train<-merge(b_hhold_train,data_BXZfamTt,by="id");rm(data_BXZfamTt)
b_hhold_train<-merge(b_hhold_train,data_jkutpUMt,by="id");rm(data_jkutpUMt)
b_hhold_train<-merge(b_hhold_train,data_lFkBekuJ,by="id");rm(data_lFkBekuJ)
b_hhold_train<-merge(b_hhold_train,data_aTEyAdSs,by="id");rm(data_aTEyAdSs)
b_hhold_train<-merge(b_hhold_train,data_TdfmGIAn,by="id");rm(data_TdfmGIAn)
b_hhold_train<-merge(b_hhold_train,data_kaVnoUbJ,by="id");rm(data_kaVnoUbJ)
b_hhold_train<-merge(b_hhold_train,data_bngqQTHD,by="id");rm(data_bngqQTHD)
b_hhold_train<-merge(b_hhold_train,data_cRQWeYKZ,by="id");rm(data_cRQWeYKZ)
b_hhold_train<-merge(b_hhold_train,data_ErqgHOEp,by="id");rm(data_ErqgHOEp)
b_hhold_train<-merge(b_hhold_train,data_Ftzawcsw,by="id");rm(data_Ftzawcsw)
b_hhold_train<-merge(b_hhold_train,data_SlqMdbUr,by="id");rm(data_SlqMdbUr)
b_hhold_train<-merge(b_hhold_train,data_jyLFRgZs,by="id");rm(data_jyLFRgZs)
b_hhold_train<-merge(b_hhold_train,data_TsredPtf,by="id");rm(data_TsredPtf)
b_hhold_train<-merge(b_hhold_train,data_pFOEMbYu,by="id");rm(data_pFOEMbYu)
b_hhold_train<-merge(b_hhold_train,data_nOoTxqCQ,by="id");rm(data_nOoTxqCQ)
b_hhold_train<-merge(b_hhold_train,data_xohFWnds,by="id");rm(data_xohFWnds)
b_hhold_train<-merge(b_hhold_train,data_JYKPCImt,by="id");rm(data_JYKPCImt)
b_hhold_train<-merge(b_hhold_train,data_wEtnhPQs,by="id");rm(data_wEtnhPQs)
b_hhold_train<-merge(b_hhold_train,data_LIoTrAzw,by="id");rm(data_LIoTrAzw)
b_hhold_train<-merge(b_hhold_train,data_IoJgECCi,by="id");rm(data_IoJgECCi)
b_hhold_train<-merge(b_hhold_train,data_YwcPaCNf,by="id");rm(data_YwcPaCNf)
b_hhold_train<-merge(b_hhold_train,data_PgXpVWEU,by="id");rm(data_PgXpVWEU)
b_hhold_train<-merge(b_hhold_train,data_ENQEzjVj,by="id");rm(data_ENQEzjVj)
b_hhold_train<-merge(b_hhold_train,data_RFLvRzHv,by="id");rm(data_RFLvRzHv)
b_hhold_train<-merge(b_hhold_train,data_xhqvDVIs,by="id");rm(data_xhqvDVIs)
b_hhold_train<-merge(b_hhold_train,data_YhbMdUgd,by="id");rm(data_YhbMdUgd)
b_hhold_train<-merge(b_hhold_train,data_cPHgLSMk,by="id");rm(data_cPHgLSMk)
b_hhold_train<-merge(b_hhold_train,data_jBZoYONA,by="id");rm(data_jBZoYONA)
b_hhold_train<-merge(b_hhold_train,data_HHbZiXXp,by="id");rm(data_HHbZiXXp)
b_hhold_train<-merge(b_hhold_train,data_DsHJnzeZ,by="id");rm(data_DsHJnzeZ)
b_hhold_train<-merge(b_hhold_train,data_PwxicsdL,by="id");rm(data_PwxicsdL)
b_hhold_train<-merge(b_hhold_train,data_UZLkbGnz,by="id");rm(data_UZLkbGnz)
b_hhold_train<-merge(b_hhold_train,data_xNhKVNgq,by="id");rm(data_xNhKVNgq)
b_hhold_train<-merge(b_hhold_train,data_nIgKFReH,by="id");rm(data_nIgKFReH)
b_hhold_train<-merge(b_hhold_train,data_FgnMveDS,by="id");rm(data_FgnMveDS)
b_hhold_train<-merge(b_hhold_train,data_NdBZKehA,by="id");rm(data_NdBZKehA)
b_hhold_train<-merge(b_hhold_train,data_mlyFwTHy,by="id");rm(data_mlyFwTHy)
b_hhold_train<-merge(b_hhold_train,data_KjMhhJdX,by="id");rm(data_KjMhhJdX)
b_hhold_train<-merge(b_hhold_train,data_zXonuRgn,by="id");rm(data_zXonuRgn)
b_hhold_train<-merge(b_hhold_train,data_MWVlKQoo,by="id");rm(data_MWVlKQoo)
b_hhold_train<-merge(b_hhold_train,data_mQezyEOr,by="id");rm(data_mQezyEOr)
b_hhold_train<-merge(b_hhold_train,data_nPlbGBjS,by="id");rm(data_nPlbGBjS)
b_hhold_train<-merge(b_hhold_train,data_nmrQVORl,by="id");rm(data_nmrQVORl)
b_hhold_train<-merge(b_hhold_train,data_KGtdytLE,by="id");rm(data_KGtdytLE)
b_hhold_train<-merge(b_hhold_train,data_DELHTNkd,by="id");rm(data_DELHTNkd)
b_hhold_train<-merge(b_hhold_train,data_rZfVzfDA,by="id");rm(data_rZfVzfDA)
b_hhold_train<-merge(b_hhold_train,data_ZHOSEFIu,by="id");rm(data_ZHOSEFIu)
b_hhold_train<-merge(b_hhold_train,data_ogUWmSXZ,by="id");rm(data_ogUWmSXZ)
b_hhold_train<-merge(b_hhold_train,data_VWMwzteg,by="id");rm(data_VWMwzteg)
b_hhold_train<-merge(b_hhold_train,data_HaaXLOfY,by="id");rm(data_HaaXLOfY)
b_hhold_train<-merge(b_hhold_train,data_NCyUzkfp,by="id");rm(data_NCyUzkfp)
b_hhold_train<-merge(b_hhold_train,data_nAjgFRel,by="id");rm(data_nAjgFRel)
b_hhold_train<-merge(b_hhold_train,data_XZUEzGLM,by="id");rm(data_XZUEzGLM)
b_hhold_train<-merge(b_hhold_train,data_OFkIQOzS,by="id");rm(data_OFkIQOzS)
b_hhold_train<-merge(b_hhold_train,data_BqXRUQgi,by="id");rm(data_BqXRUQgi)
b_hhold_train<-merge(b_hhold_train,data_ywnHMkvq,by="id");rm(data_ywnHMkvq)
b_hhold_train<-merge(b_hhold_train,data_eKkwQtwX,by="id");rm(data_eKkwQtwX)
b_hhold_train<-merge(b_hhold_train,data_fwRLKHlN,by="id");rm(data_fwRLKHlN)
b_hhold_train<-merge(b_hhold_train,data_jUwlkffQ,by="id");rm(data_jUwlkffQ)
b_hhold_train<-merge(b_hhold_train,data_DAeoUuuN,by="id");rm(data_DAeoUuuN)
b_hhold_train<-merge(b_hhold_train,data_gsofZtJJ,by="id");rm(data_gsofZtJJ)
b_hhold_train<-merge(b_hhold_train,data_HQPtUibh,by="id");rm(data_HQPtUibh)
b_hhold_train<-merge(b_hhold_train,data_aqYWloSo,by="id");rm(data_aqYWloSo)
b_hhold_train<-merge(b_hhold_train,data_RUTkmJrl,by="id");rm(data_RUTkmJrl)
b_hhold_train<-merge(b_hhold_train,data_tQzcGkNE,by="id");rm(data_tQzcGkNE)
b_hhold_train<-merge(b_hhold_train,data_VszNwfYx,by="id");rm(data_VszNwfYx)
b_hhold_train<-merge(b_hhold_train,data_hnwVYJyV,by="id");rm(data_hnwVYJyV)
b_hhold_train<-merge(b_hhold_train,data_RsMBXisy,by="id");rm(data_RsMBXisy)
b_hhold_train<-merge(b_hhold_train,data_MiGIkxpV,by="id");rm(data_MiGIkxpV)
b_hhold_train<-merge(b_hhold_train,data_xbOnnZEV,by="id");rm(data_xbOnnZEV)
b_hhold_train<-merge(b_hhold_train,data_cGaHwCJA,by="id");rm(data_cGaHwCJA)
b_hhold_train<-merge(b_hhold_train,data_dfchpzYE,by="id");rm(data_dfchpzYE)
b_hhold_train<-merge(b_hhold_train,data_fwBNLzWK,by="id");rm(data_fwBNLzWK)
b_hhold_train<-merge(b_hhold_train,data_lLoRmWKX,by="id");rm(data_lLoRmWKX)
b_hhold_train<-merge(b_hhold_train,data_GhzvKcjl,by="id");rm(data_GhzvKcjl)
b_hhold_train<-merge(b_hhold_train,data_EpWsJmrF,by="id");rm(data_EpWsJmrF)
b_hhold_train<-merge(b_hhold_train,data_wpoJgbis,by="id");rm(data_wpoJgbis)
b_hhold_train<-merge(b_hhold_train,data_KyTRKtbW,by="id");rm(data_KyTRKtbW)
b_hhold_train<-merge(b_hhold_train,data_xlJGUBXM,by="id");rm(data_xlJGUBXM)
b_hhold_train<-merge(b_hhold_train,data_zuvYUDSL,by="id");rm(data_zuvYUDSL)
b_hhold_train<-merge(b_hhold_train,data_ozvFfhhM,by="id");rm(data_ozvFfhhM)
b_hhold_train<-merge(b_hhold_train,data_ljaNZowA,by="id");rm(data_ljaNZowA)
b_hhold_train<-merge(b_hhold_train,data_sbjoLEKh,by="id");rm(data_sbjoLEKh)
b_hhold_train<-merge(b_hhold_train,data_pyvZUOyi,by="id");rm(data_pyvZUOyi)
b_hhold_train<-merge(b_hhold_train,data_FldbnriM,by="id");rm(data_FldbnriM)
b_hhold_train<-merge(b_hhold_train,data_FyXQULwx,by="id");rm(data_FyXQULwx)
b_hhold_train<-merge(b_hhold_train,data_UUYYcars,by="id");rm(data_UUYYcars)
b_hhold_train<-merge(b_hhold_train,data_xMysunyA,by="id");rm(data_xMysunyA)
b_hhold_train<-merge(b_hhold_train,data_FOIfEcny,by="id");rm(data_FOIfEcny)
b_hhold_train<-merge(b_hhold_train,data_BhPvRtpj,by="id");rm(data_BhPvRtpj)
b_hhold_train<-merge(b_hhold_train,data_JniMXoSr,by="id");rm(data_JniMXoSr)
b_hhold_train<-merge(b_hhold_train,data_AFSIVjPG,by="id");rm(data_AFSIVjPG)
b_hhold_train<-merge(b_hhold_train,data_lnMlvpes,by="id");rm(data_lnMlvpes)
b_hhold_train<-merge(b_hhold_train,data_HrXGKbwr,by="id");rm(data_HrXGKbwr)
b_hhold_train<-merge(b_hhold_train,data_NUefhhHz,by="id");rm(data_NUefhhHz)
b_hhold_train<-merge(b_hhold_train,data_UaUnOdpg,by="id");rm(data_UaUnOdpg)
b_hhold_train<-merge(b_hhold_train,data_QIQcRKCg,by="id");rm(data_QIQcRKCg)
b_hhold_train<-merge(b_hhold_train,data_yNHqwYaJ,by="id");rm(data_yNHqwYaJ)
b_hhold_train<-merge(b_hhold_train,data_rWlPNhUy,by="id");rm(data_rWlPNhUy)
b_hhold_train<-merge(b_hhold_train,data_QcuPNLAv,by="id");rm(data_QcuPNLAv)
b_hhold_train<-merge(b_hhold_train,data_nkxrhykC,by="id");rm(data_nkxrhykC)
b_hhold_train<-merge(b_hhold_train,data_zTEEwTzG,by="id");rm(data_zTEEwTzG)
b_hhold_train<-merge(b_hhold_train,data_NMsLrKWd,by="id");rm(data_NMsLrKWd)
b_hhold_train<-merge(b_hhold_train,data_iHCKmQSy,by="id");rm(data_iHCKmQSy)
b_hhold_train<-merge(b_hhold_train,data_UPswDJlm,by="id");rm(data_UPswDJlm)
b_hhold_train<-merge(b_hhold_train,data_OhKTEjVy,by="id");rm(data_OhKTEjVy)
b_hhold_train<-merge(b_hhold_train,data_jRXAvmTH,by="id");rm(data_jRXAvmTH)
b_hhold_train<-merge(b_hhold_train,data_FHoVOXib,by="id");rm(data_FHoVOXib)
b_hhold_train<-merge(b_hhold_train,data_OATvAQNG,by="id");rm(data_OATvAQNG)
b_hhold_train<-merge(b_hhold_train,data_teSzyTms,by="id");rm(data_teSzyTms)
b_hhold_train<-merge(b_hhold_train,data_FsUFnmgF,by="id");rm(data_FsUFnmgF)
b_hhold_train<-merge(b_hhold_train,data_uDVGRBVU,by="id");rm(data_uDVGRBVU)
b_hhold_train<-merge(b_hhold_train,data_WCMouTCp,by="id");rm(data_WCMouTCp)
b_hhold_train<-merge(b_hhold_train,data_VKUGzaxx,by="id");rm(data_VKUGzaxx)
b_hhold_train<-merge(b_hhold_train,data_tkFVflRJ,by="id");rm(data_tkFVflRJ)
b_hhold_train<-merge(b_hhold_train,data_qhffLQpJ,by="id");rm(data_qhffLQpJ)
b_hhold_train<-merge(b_hhold_train,data_dFaxStnz,by="id");rm(data_dFaxStnz)
b_hhold_train<-merge(b_hhold_train,data_EzGVhUlW,by="id");rm(data_EzGVhUlW)
b_hhold_train<-merge(b_hhold_train,data_pDeMFniB,by="id");rm(data_pDeMFniB)
b_hhold_train<-merge(b_hhold_train,data_AxEjAWSE,by="id");rm(data_AxEjAWSE)
b_hhold_train<-merge(b_hhold_train,data_MhvfpnqH,by="id");rm(data_MhvfpnqH)
b_hhold_train<-merge(b_hhold_train,data_jdYXWZgD,by="id");rm(data_jdYXWZgD)
b_hhold_train<-merge(b_hhold_train,data_LLZtRxnK,by="id");rm(data_LLZtRxnK)
b_hhold_train<-merge(b_hhold_train,data_CtIAiLwz,by="id");rm(data_CtIAiLwz)
b_hhold_train<-merge(b_hhold_train,data_NPNqQdIn,by="id");rm(data_NPNqQdIn)
b_hhold_train<-merge(b_hhold_train,data_qzOZZsuS,by="id");rm(data_qzOZZsuS)
b_hhold_train<-merge(b_hhold_train,data_vquBDhol,by="id");rm(data_vquBDhol)
b_hhold_train<-merge(b_hhold_train,data_MMWrfMBi,by="id");rm(data_MMWrfMBi)
b_hhold_train<-merge(b_hhold_train,data_GshWgURK,by="id");rm(data_GshWgURK)
b_hhold_train<-merge(b_hhold_train,data_LSpCPhcU,by="id");rm(data_LSpCPhcU)
b_hhold_train<-merge(b_hhold_train,data_pHYVhLJD,by="id");rm(data_pHYVhLJD)
b_hhold_train<-merge(b_hhold_train,data_NocVJZYG,by="id");rm(data_NocVJZYG)
b_hhold_train<-merge(b_hhold_train,data_zhbhQewN,by="id");rm(data_zhbhQewN)
b_hhold_train<-merge(b_hhold_train,data_qxVAoxyX,by="id");rm(data_qxVAoxyX)
b_hhold_train<-merge(b_hhold_train,data_sWADnjxA,by="id");rm(data_sWADnjxA)
b_hhold_train<-merge(b_hhold_train,data_zgJdRdgg,by="id");rm(data_zgJdRdgg)
b_hhold_train<-merge(b_hhold_train,data_rxwugNti,by="id");rm(data_rxwugNti)
b_hhold_train<-merge(b_hhold_train,data_XIHNcHXI,by="id");rm(data_XIHNcHXI)
b_hhold_train<-merge(b_hhold_train,data_tugScLvF,by="id");rm(data_tugScLvF)
b_hhold_train<-merge(b_hhold_train,data_xTZOLcSX,by="id");rm(data_xTZOLcSX)
b_hhold_train<-merge(b_hhold_train,data_eWNUvdjK,by="id");rm(data_eWNUvdjK)
b_hhold_train<-merge(b_hhold_train,data_yxQmKfsS,by="id");rm(data_yxQmKfsS)
b_hhold_train<-merge(b_hhold_train,data_PyTDmsQl,by="id");rm(data_PyTDmsQl)
b_hhold_train<-merge(b_hhold_train,data_CnQHDRVZ,by="id");rm(data_CnQHDRVZ)
b_hhold_train<-merge(b_hhold_train,data_VxXEkbdS,by="id");rm(data_VxXEkbdS)
b_hhold_train<-merge(b_hhold_train,data_vVyGhGoB,by="id");rm(data_vVyGhGoB)
b_hhold_train<-merge(b_hhold_train,data_qRplnnEM,by="id");rm(data_qRplnnEM)
b_hhold_train<-merge(b_hhold_train,data_SCLDdPrm,by="id");rm(data_SCLDdPrm)
b_hhold_train<-merge(b_hhold_train,data_HcutWGCs,by="id");rm(data_HcutWGCs)
b_hhold_train<-merge(b_hhold_train,data_GlkLFREL,by="id");rm(data_GlkLFREL)
b_hhold_train<-merge(b_hhold_train,data_NAZxDkiV,by="id");rm(data_NAZxDkiV)
b_hhold_train<-merge(b_hhold_train,data_yjAfWuLb,by="id");rm(data_yjAfWuLb)
b_hhold_train<-merge(b_hhold_train,data_GlktDEEv,by="id");rm(data_GlktDEEv)
b_hhold_train<-merge(b_hhold_train,data_IIvMcTrH,by="id");rm(data_IIvMcTrH)
b_hhold_train<-merge(b_hhold_train,data_JbDBFPPd,by="id");rm(data_JbDBFPPd)
b_hhold_train<-merge(b_hhold_train,data_clCRDApV,by="id");rm(data_clCRDApV)
b_hhold_train<-merge(b_hhold_train,data_aYGuxgyP,by="id");rm(data_aYGuxgyP)
b_hhold_train<-merge(b_hhold_train,data_NZYkmhkD,by="id");rm(data_NZYkmhkD)
b_hhold_train<-merge(b_hhold_train,data_fxWioPPP,by="id");rm(data_fxWioPPP)
b_hhold_train<-merge(b_hhold_train,data_DWmTWcUm,by="id");rm(data_DWmTWcUm)
b_hhold_train<-merge(b_hhold_train,data_PxgyaWYq,by="id");rm(data_PxgyaWYq)
b_hhold_train<-merge(b_hhold_train,data_cavdrXpj,by="id");rm(data_cavdrXpj)



data_BoxViLPz<-aggregate(BoxViLPz~id,b_indiv_train,sum)
data_qlLzyqpP<-aggregate(qlLzyqpP~id,b_indiv_train,sum)
data_unRAgFtX<-aggregate(unRAgFtX~id,b_indiv_train,sum)
data_TJGiunYp<-aggregate(TJGiunYp~id,b_indiv_train,sum)
data_WmKLEUcd<-aggregate(WmKLEUcd~id,b_indiv_train,sum)
data_DYgxQeEi<-aggregate(DYgxQeEi~id,b_indiv_train,sum)
data_jfsTwowc<-aggregate(jfsTwowc~id,b_indiv_train,sum)
data_MGfpfHam<-aggregate(MGfpfHam~id,b_indiv_train,sum)
data_esHWAAyG<-aggregate(esHWAAyG~id,b_indiv_train,sum)
data_DtcKwIEv<-aggregate(DtcKwIEv~id,b_indiv_train,sum)
data_ETgxnJOM<-aggregate(ETgxnJOM~id,b_indiv_train,sum)
data_gKsBCLMY<-aggregate(gKsBCLMY~id,b_indiv_train,sum)
data_TZDgOhYY<-aggregate(TZDgOhYY~id,b_indiv_train,sum)
data_sWElQwuC<-aggregate(sWElQwuC~id,b_indiv_train,sum)
data_jzBRbsEG<-aggregate(jzBRbsEG~id,b_indiv_train,sum)
data_CLTXEwmz<-aggregate(CLTXEwmz~id,b_indiv_train,sum)
data_WqEZQuJP<-aggregate(WqEZQuJP~id,b_indiv_train,sum)
data_dnmwvCng<-aggregate(dnmwvCng~id,b_indiv_train,sum)
data_DSttkpSI<-aggregate(DSttkpSI~id,b_indiv_train,sum)
data_sIiSADFG<-aggregate(sIiSADFG~id,b_indiv_train,sum)
data_uDmhgsaQ<-aggregate(uDmhgsaQ~id,b_indiv_train,sum)
data_hdDTwJhQ<-aggregate(hdDTwJhQ~id,b_indiv_train,sum)
data_AJgudnHB<-aggregate(AJgudnHB~id,b_indiv_train,sum)
data_iZhWxnWa<-aggregate(iZhWxnWa~id,b_indiv_train,sum)
data_fyfDnyQk<-aggregate(fyfDnyQk~id,b_indiv_train,sum)
data_wJthinfa<-aggregate(wJthinfa~id,b_indiv_train,sum)
data_nxAFXxLQ<-aggregate(nxAFXxLQ~id,b_indiv_train,sum)
data_mAeaImix<-aggregate(mAeaImix~id,b_indiv_train,sum)
data_HZqPmvkr<-aggregate(HZqPmvkr~id,b_indiv_train,sum)
data_ulQCDoYe<-aggregate(ulQCDoYe~id,b_indiv_train,sum)
data_tzYvQeOb<-aggregate(tzYvQeOb~id,b_indiv_train,sum)
data_NfpXxGQk<-aggregate(NfpXxGQk~id,b_indiv_train,sum)





b_hhold_train<-merge(b_hhold_train,data_BoxViLPz,by="id",all.x = TRUE);rm(data_BoxViLPz)
b_hhold_train<-merge(b_hhold_train,data_qlLzyqpP,by="id",all.x = TRUE);rm(data_qlLzyqpP)
b_hhold_train<-merge(b_hhold_train,data_unRAgFtX,by="id",all.x = TRUE);rm(data_unRAgFtX)
b_hhold_train<-merge(b_hhold_train,data_TJGiunYp,by="id",all.x = TRUE);rm(data_TJGiunYp)
b_hhold_train<-merge(b_hhold_train,data_WmKLEUcd,by="id",all.x = TRUE);rm(data_WmKLEUcd)
b_hhold_train<-merge(b_hhold_train,data_DYgxQeEi,by="id",all.x = TRUE);rm(data_DYgxQeEi)
b_hhold_train<-merge(b_hhold_train,data_jfsTwowc,by="id",all.x = TRUE);rm(data_jfsTwowc)
b_hhold_train<-merge(b_hhold_train,data_MGfpfHam,by="id",all.x = TRUE);rm(data_MGfpfHam)
b_hhold_train<-merge(b_hhold_train,data_esHWAAyG,by="id",all.x = TRUE);rm(data_esHWAAyG)
b_hhold_train<-merge(b_hhold_train,data_DtcKwIEv,by="id",all.x = TRUE);rm(data_DtcKwIEv)
b_hhold_train<-merge(b_hhold_train,data_ETgxnJOM,by="id",all.x = TRUE);rm(data_ETgxnJOM)
b_hhold_train<-merge(b_hhold_train,data_gKsBCLMY,by="id",all.x = TRUE);rm(data_gKsBCLMY)
b_hhold_train<-merge(b_hhold_train,data_TZDgOhYY,by="id",all.x = TRUE);rm(data_TZDgOhYY)
b_hhold_train<-merge(b_hhold_train,data_sWElQwuC,by="id",all.x = TRUE);rm(data_sWElQwuC)
b_hhold_train<-merge(b_hhold_train,data_jzBRbsEG,by="id",all.x = TRUE);rm(data_jzBRbsEG)
b_hhold_train<-merge(b_hhold_train,data_CLTXEwmz,by="id",all.x = TRUE);rm(data_CLTXEwmz)
b_hhold_train<-merge(b_hhold_train,data_WqEZQuJP,by="id",all.x = TRUE);rm(data_WqEZQuJP)
b_hhold_train<-merge(b_hhold_train,data_dnmwvCng,by="id",all.x = TRUE);rm(data_dnmwvCng)
b_hhold_train<-merge(b_hhold_train,data_DSttkpSI,by="id",all.x = TRUE);rm(data_DSttkpSI)
b_hhold_train<-merge(b_hhold_train,data_sIiSADFG,by="id",all.x = TRUE);rm(data_sIiSADFG)
b_hhold_train<-merge(b_hhold_train,data_uDmhgsaQ,by="id",all.x = TRUE);rm(data_uDmhgsaQ)
b_hhold_train<-merge(b_hhold_train,data_hdDTwJhQ,by="id",all.x = TRUE);rm(data_hdDTwJhQ)
b_hhold_train<-merge(b_hhold_train,data_AJgudnHB,by="id",all.x = TRUE);rm(data_AJgudnHB)
b_hhold_train<-merge(b_hhold_train,data_iZhWxnWa,by="id",all.x = TRUE);rm(data_iZhWxnWa)
b_hhold_train<-merge(b_hhold_train,data_fyfDnyQk,by="id",all.x = TRUE);rm(data_fyfDnyQk)
b_hhold_train<-merge(b_hhold_train,data_wJthinfa,by="id",all.x = TRUE);rm(data_wJthinfa)
b_hhold_train<-merge(b_hhold_train,data_nxAFXxLQ,by="id",all.x = TRUE);rm(data_nxAFXxLQ)
b_hhold_train<-merge(b_hhold_train,data_mAeaImix,by="id",all.x = TRUE);rm(data_mAeaImix)
b_hhold_train<-merge(b_hhold_train,data_HZqPmvkr,by="id",all.x = TRUE);rm(data_HZqPmvkr)
b_hhold_train<-merge(b_hhold_train,data_ulQCDoYe,by="id",all.x = TRUE);rm(data_ulQCDoYe)
b_hhold_train<-merge(b_hhold_train,data_tzYvQeOb,by="id",all.x = TRUE);rm(data_tzYvQeOb)
b_hhold_train<-merge(b_hhold_train,data_NfpXxGQk,by="id",all.x = TRUE);rm(data_NfpXxGQk)


b_train<-b_hhold_train

b_train_cat<-sapply(b_train, is.factor)
b_train_cat<-b_train[,b_train_cat]
b_train_con<-sapply(b_train, is.numeric)
b_train_con<-b_train[,b_train_con]
y<-data.frame(poor=b_train$poor)
names(b_train_cat)
b_train_dum<-dummy.data.frame(b_train_cat[-361])
b_train_com<-cbind(b_train_con,b_train_dum,y)

nearZeroVar(b_train_com[-c(1,3069)])


if (length(nearZeroVar(b_train_com[-c(1,3069)])) > 0) {
  b_train_com <- b_train_com[, -nearZeroVar(b_train_com)] 
}
sum(is.na(b_train_com))
colSums(is.na(b_train_com))

b_train_com <- b_train_com[lapply(b_train_com, function(x) sum(is.na(x)) / length(x) ) < 0.1 ]

rm(b_indiv_train);rm(b_hhold_train);rm(b_train);rm(b_train_cat);rm(b_train_con);rm(b_train_dum);rm(y)

library(reshape2)

b_hhold_test<-read.csv('b_hhold_test.csv')
b_indiv_test<-read.csv('b_indiv_test.csv')

#write.csv(names(b_indiv_test),'b_names.csv',row.names = F)
#lapply(b_indiv_test, class)
#write.csv(lapply(b_indiv_test, class),'b1_names.csv',row.names = F)
data_MmKGUOrD<-dcast(b_indiv_test,id~MmKGUOrD,value.var="iid")
data_splgBZfe<-dcast(b_indiv_test,id~splgBZfe,value.var="iid")
data_JTCCBpjX<-dcast(b_indiv_test,id~JTCCBpjX,value.var="iid")
data_akGaJaYF<-dcast(b_indiv_test,id~akGaJaYF,value.var="iid")
data_eYoMkEyN<-dcast(b_indiv_test,id~eYoMkEyN,value.var="iid")
data_bmhTgzYu<-dcast(b_indiv_test,id~bmhTgzYu,value.var="iid")
data_GjxOmHgp<-dcast(b_indiv_test,id~GjxOmHgp,value.var="iid")
data_mYMBWfIH<-dcast(b_indiv_test,id~mYMBWfIH,value.var="iid")
data_SZucUQmM<-dcast(b_indiv_test,id~SZucUQmM,value.var="iid")
data_EfqFGRSF<-dcast(b_indiv_test,id~EfqFGRSF,value.var="iid")
data_plDSQDzp<-dcast(b_indiv_test,id~plDSQDzp,value.var="iid")
data_jyZvBZlo<-dcast(b_indiv_test,id~jyZvBZlo,value.var="iid")
data_gyxBUEPe<-dcast(b_indiv_test,id~gyxBUEPe,value.var="iid")
data_lTdxcpBA<-dcast(b_indiv_test,id~lTdxcpBA,value.var="iid")
data_yoijDqAm<-dcast(b_indiv_test,id~yoijDqAm,value.var="iid")
data_LkhgHzsx<-dcast(b_indiv_test,id~LkhgHzsx,value.var="iid")
data_UUYXAsfo<-dcast(b_indiv_test,id~UUYXAsfo,value.var="iid")
data_IPBrAaYt<-dcast(b_indiv_test,id~IPBrAaYt,value.var="iid")
data_hCgDHGEc<-dcast(b_indiv_test,id~hCgDHGEc,value.var="iid")
data_GFXSuQvB<-dcast(b_indiv_test,id~GFXSuQvB,value.var="iid")
data_UPtsFglH<-dcast(b_indiv_test,id~UPtsFglH,value.var="iid")
data_HZEsXrsF<-dcast(b_indiv_test,id~HZEsXrsF,value.var="iid")
data_kgVoFHRj<-dcast(b_indiv_test,id~kgVoFHRj,value.var="iid")
data_pqbNHKuK<-dcast(b_indiv_test,id~pqbNHKuK,value.var="iid")
data_gEqzZWXR<-dcast(b_indiv_test,id~gEqzZWXR,value.var="iid")
data_UkXhNUcd<-dcast(b_indiv_test,id~UkXhNUcd,value.var="iid")
data_hggXZmdr<-dcast(b_indiv_test,id~hggXZmdr,value.var="iid")
data_uyhBLPFL<-dcast(b_indiv_test,id~uyhBLPFL,value.var="iid")
data_hwJpBxAl<-dcast(b_indiv_test,id~hwJpBxAl,value.var="iid")
data_BXZfamTt<-dcast(b_indiv_test,id~BXZfamTt,value.var="iid")
data_jkutpUMt<-dcast(b_indiv_test,id~jkutpUMt,value.var="iid")
data_lFkBekuJ<-dcast(b_indiv_test,id~lFkBekuJ,value.var="iid")
data_aTEyAdSs<-dcast(b_indiv_test,id~aTEyAdSs,value.var="iid")
data_TdfmGIAn<-dcast(b_indiv_test,id~TdfmGIAn,value.var="iid")
data_kaVnoUbJ<-dcast(b_indiv_test,id~kaVnoUbJ,value.var="iid")
data_bngqQTHD<-dcast(b_indiv_test,id~bngqQTHD,value.var="iid")
data_cRQWeYKZ<-dcast(b_indiv_test,id~cRQWeYKZ,value.var="iid")
data_ErqgHOEp<-dcast(b_indiv_test,id~ErqgHOEp,value.var="iid")
data_Ftzawcsw<-dcast(b_indiv_test,id~Ftzawcsw,value.var="iid")
data_SlqMdbUr<-dcast(b_indiv_test,id~SlqMdbUr,value.var="iid")
data_jyLFRgZs<-dcast(b_indiv_test,id~jyLFRgZs,value.var="iid")
data_TsredPtf<-dcast(b_indiv_test,id~TsredPtf,value.var="iid")
data_pFOEMbYu<-dcast(b_indiv_test,id~pFOEMbYu,value.var="iid")
data_nOoTxqCQ<-dcast(b_indiv_test,id~nOoTxqCQ,value.var="iid")
data_xohFWnds<-dcast(b_indiv_test,id~xohFWnds,value.var="iid")
data_JYKPCImt<-dcast(b_indiv_test,id~JYKPCImt,value.var="iid")
data_wEtnhPQs<-dcast(b_indiv_test,id~wEtnhPQs,value.var="iid")
data_LIoTrAzw<-dcast(b_indiv_test,id~LIoTrAzw,value.var="iid")
data_IoJgECCi<-dcast(b_indiv_test,id~IoJgECCi,value.var="iid")
data_YwcPaCNf<-dcast(b_indiv_test,id~YwcPaCNf,value.var="iid")
data_PgXpVWEU<-dcast(b_indiv_test,id~PgXpVWEU,value.var="iid")
data_ENQEzjVj<-dcast(b_indiv_test,id~ENQEzjVj,value.var="iid")
data_RFLvRzHv<-dcast(b_indiv_test,id~RFLvRzHv,value.var="iid")
data_xhqvDVIs<-dcast(b_indiv_test,id~xhqvDVIs,value.var="iid")
data_YhbMdUgd<-dcast(b_indiv_test,id~YhbMdUgd,value.var="iid")
data_cPHgLSMk<-dcast(b_indiv_test,id~cPHgLSMk,value.var="iid")
data_jBZoYONA<-dcast(b_indiv_test,id~jBZoYONA,value.var="iid")
data_HHbZiXXp<-dcast(b_indiv_test,id~HHbZiXXp,value.var="iid")
data_DsHJnzeZ<-dcast(b_indiv_test,id~DsHJnzeZ,value.var="iid")
data_PwxicsdL<-dcast(b_indiv_test,id~PwxicsdL,value.var="iid")
data_UZLkbGnz<-dcast(b_indiv_test,id~UZLkbGnz,value.var="iid")
data_xNhKVNgq<-dcast(b_indiv_test,id~xNhKVNgq,value.var="iid")
data_nIgKFReH<-dcast(b_indiv_test,id~nIgKFReH,value.var="iid")
data_FgnMveDS<-dcast(b_indiv_test,id~FgnMveDS,value.var="iid")
data_NdBZKehA<-dcast(b_indiv_test,id~NdBZKehA,value.var="iid")
data_mlyFwTHy<-dcast(b_indiv_test,id~mlyFwTHy,value.var="iid")
data_KjMhhJdX<-dcast(b_indiv_test,id~KjMhhJdX,value.var="iid")
data_zXonuRgn<-dcast(b_indiv_test,id~zXonuRgn,value.var="iid")
data_MWVlKQoo<-dcast(b_indiv_test,id~MWVlKQoo,value.var="iid")
data_mQezyEOr<-dcast(b_indiv_test,id~mQezyEOr,value.var="iid")
data_nPlbGBjS<-dcast(b_indiv_test,id~nPlbGBjS,value.var="iid")
data_nmrQVORl<-dcast(b_indiv_test,id~nmrQVORl,value.var="iid")
data_KGtdytLE<-dcast(b_indiv_test,id~KGtdytLE,value.var="iid")
data_DELHTNkd<-dcast(b_indiv_test,id~DELHTNkd,value.var="iid")
data_rZfVzfDA<-dcast(b_indiv_test,id~rZfVzfDA,value.var="iid")
data_ZHOSEFIu<-dcast(b_indiv_test,id~ZHOSEFIu,value.var="iid")
data_ogUWmSXZ<-dcast(b_indiv_test,id~ogUWmSXZ,value.var="iid")
data_VWMwzteg<-dcast(b_indiv_test,id~VWMwzteg,value.var="iid")
data_HaaXLOfY<-dcast(b_indiv_test,id~HaaXLOfY,value.var="iid")
data_NCyUzkfp<-dcast(b_indiv_test,id~NCyUzkfp,value.var="iid")
data_nAjgFRel<-dcast(b_indiv_test,id~nAjgFRel,value.var="iid")
data_XZUEzGLM<-dcast(b_indiv_test,id~XZUEzGLM,value.var="iid")
data_OFkIQOzS<-dcast(b_indiv_test,id~OFkIQOzS,value.var="iid")
data_BqXRUQgi<-dcast(b_indiv_test,id~BqXRUQgi,value.var="iid")
data_ywnHMkvq<-dcast(b_indiv_test,id~ywnHMkvq,value.var="iid")
data_eKkwQtwX<-dcast(b_indiv_test,id~eKkwQtwX,value.var="iid")
data_fwRLKHlN<-dcast(b_indiv_test,id~fwRLKHlN,value.var="iid")
data_jUwlkffQ<-dcast(b_indiv_test,id~jUwlkffQ,value.var="iid")
data_DAeoUuuN<-dcast(b_indiv_test,id~DAeoUuuN,value.var="iid")
data_gsofZtJJ<-dcast(b_indiv_test,id~gsofZtJJ,value.var="iid")
data_HQPtUibh<-dcast(b_indiv_test,id~HQPtUibh,value.var="iid")
data_aqYWloSo<-dcast(b_indiv_test,id~aqYWloSo,value.var="iid")
data_RUTkmJrl<-dcast(b_indiv_test,id~RUTkmJrl,value.var="iid")
data_tQzcGkNE<-dcast(b_indiv_test,id~tQzcGkNE,value.var="iid")
data_VszNwfYx<-dcast(b_indiv_test,id~VszNwfYx,value.var="iid")
data_hnwVYJyV<-dcast(b_indiv_test,id~hnwVYJyV,value.var="iid")
data_RsMBXisy<-dcast(b_indiv_test,id~RsMBXisy,value.var="iid")
data_MiGIkxpV<-dcast(b_indiv_test,id~MiGIkxpV,value.var="iid")
data_xbOnnZEV<-dcast(b_indiv_test,id~xbOnnZEV,value.var="iid")
data_cGaHwCJA<-dcast(b_indiv_test,id~cGaHwCJA,value.var="iid")
data_dfchpzYE<-dcast(b_indiv_test,id~dfchpzYE,value.var="iid")
data_fwBNLzWK<-dcast(b_indiv_test,id~fwBNLzWK,value.var="iid")
data_lLoRmWKX<-dcast(b_indiv_test,id~lLoRmWKX,value.var="iid")
data_GhzvKcjl<-dcast(b_indiv_test,id~GhzvKcjl,value.var="iid")
data_EpWsJmrF<-dcast(b_indiv_test,id~EpWsJmrF,value.var="iid")
data_wpoJgbis<-dcast(b_indiv_test,id~wpoJgbis,value.var="iid")
data_KyTRKtbW<-dcast(b_indiv_test,id~KyTRKtbW,value.var="iid")
data_xlJGUBXM<-dcast(b_indiv_test,id~xlJGUBXM,value.var="iid")
data_zuvYUDSL<-dcast(b_indiv_test,id~zuvYUDSL,value.var="iid")
data_ozvFfhhM<-dcast(b_indiv_test,id~ozvFfhhM,value.var="iid")
data_ljaNZowA<-dcast(b_indiv_test,id~ljaNZowA,value.var="iid")
data_sbjoLEKh<-dcast(b_indiv_test,id~sbjoLEKh,value.var="iid")
data_pyvZUOyi<-dcast(b_indiv_test,id~pyvZUOyi,value.var="iid")
data_FldbnriM<-dcast(b_indiv_test,id~FldbnriM,value.var="iid")
data_FyXQULwx<-dcast(b_indiv_test,id~FyXQULwx,value.var="iid")
data_UUYYcars<-dcast(b_indiv_test,id~UUYYcars,value.var="iid")
data_xMysunyA<-dcast(b_indiv_test,id~xMysunyA,value.var="iid")
data_FOIfEcny<-dcast(b_indiv_test,id~FOIfEcny,value.var="iid")
data_BhPvRtpj<-dcast(b_indiv_test,id~BhPvRtpj,value.var="iid")
data_JniMXoSr<-dcast(b_indiv_test,id~JniMXoSr,value.var="iid")
data_AFSIVjPG<-dcast(b_indiv_test,id~AFSIVjPG,value.var="iid")
data_lnMlvpes<-dcast(b_indiv_test,id~lnMlvpes,value.var="iid")
data_HrXGKbwr<-dcast(b_indiv_test,id~HrXGKbwr,value.var="iid")
data_NUefhhHz<-dcast(b_indiv_test,id~NUefhhHz,value.var="iid")
data_UaUnOdpg<-dcast(b_indiv_test,id~UaUnOdpg,value.var="iid")
data_QIQcRKCg<-dcast(b_indiv_test,id~QIQcRKCg,value.var="iid")
data_yNHqwYaJ<-dcast(b_indiv_test,id~yNHqwYaJ,value.var="iid")
data_rWlPNhUy<-dcast(b_indiv_test,id~rWlPNhUy,value.var="iid")
data_QcuPNLAv<-dcast(b_indiv_test,id~QcuPNLAv,value.var="iid")
data_nkxrhykC<-dcast(b_indiv_test,id~nkxrhykC,value.var="iid")
data_zTEEwTzG<-dcast(b_indiv_test,id~zTEEwTzG,value.var="iid")
data_NMsLrKWd<-dcast(b_indiv_test,id~NMsLrKWd,value.var="iid")
data_iHCKmQSy<-dcast(b_indiv_test,id~iHCKmQSy,value.var="iid")
data_UPswDJlm<-dcast(b_indiv_test,id~UPswDJlm,value.var="iid")
data_OhKTEjVy<-dcast(b_indiv_test,id~OhKTEjVy,value.var="iid")
data_jRXAvmTH<-dcast(b_indiv_test,id~jRXAvmTH,value.var="iid")
data_FHoVOXib<-dcast(b_indiv_test,id~FHoVOXib,value.var="iid")
data_OATvAQNG<-dcast(b_indiv_test,id~OATvAQNG,value.var="iid")
data_teSzyTms<-dcast(b_indiv_test,id~teSzyTms,value.var="iid")
data_FsUFnmgF<-dcast(b_indiv_test,id~FsUFnmgF,value.var="iid")
data_uDVGRBVU<-dcast(b_indiv_test,id~uDVGRBVU,value.var="iid")
data_WCMouTCp<-dcast(b_indiv_test,id~WCMouTCp,value.var="iid")
data_VKUGzaxx<-dcast(b_indiv_test,id~VKUGzaxx,value.var="iid")
data_tkFVflRJ<-dcast(b_indiv_test,id~tkFVflRJ,value.var="iid")
data_qhffLQpJ<-dcast(b_indiv_test,id~qhffLQpJ,value.var="iid")
data_dFaxStnz<-dcast(b_indiv_test,id~dFaxStnz,value.var="iid")
data_EzGVhUlW<-dcast(b_indiv_test,id~EzGVhUlW,value.var="iid")
data_pDeMFniB<-dcast(b_indiv_test,id~pDeMFniB,value.var="iid")
data_AxEjAWSE<-dcast(b_indiv_test,id~AxEjAWSE,value.var="iid")
data_MhvfpnqH<-dcast(b_indiv_test,id~MhvfpnqH,value.var="iid")
data_jdYXWZgD<-dcast(b_indiv_test,id~jdYXWZgD,value.var="iid")
data_LLZtRxnK<-dcast(b_indiv_test,id~LLZtRxnK,value.var="iid")
data_CtIAiLwz<-dcast(b_indiv_test,id~CtIAiLwz,value.var="iid")
data_NPNqQdIn<-dcast(b_indiv_test,id~NPNqQdIn,value.var="iid")
data_qzOZZsuS<-dcast(b_indiv_test,id~qzOZZsuS,value.var="iid")
data_vquBDhol<-dcast(b_indiv_test,id~vquBDhol,value.var="iid")
data_MMWrfMBi<-dcast(b_indiv_test,id~MMWrfMBi,value.var="iid")
data_GshWgURK<-dcast(b_indiv_test,id~GshWgURK,value.var="iid")
data_LSpCPhcU<-dcast(b_indiv_test,id~LSpCPhcU,value.var="iid")
data_pHYVhLJD<-dcast(b_indiv_test,id~pHYVhLJD,value.var="iid")
data_NocVJZYG<-dcast(b_indiv_test,id~NocVJZYG,value.var="iid")
data_zhbhQewN<-dcast(b_indiv_test,id~zhbhQewN,value.var="iid")
data_qxVAoxyX<-dcast(b_indiv_test,id~qxVAoxyX,value.var="iid")
data_sWADnjxA<-dcast(b_indiv_test,id~sWADnjxA,value.var="iid")
data_zgJdRdgg<-dcast(b_indiv_test,id~zgJdRdgg,value.var="iid")
data_rxwugNti<-dcast(b_indiv_test,id~rxwugNti,value.var="iid")
data_XIHNcHXI<-dcast(b_indiv_test,id~XIHNcHXI,value.var="iid")
data_tugScLvF<-dcast(b_indiv_test,id~tugScLvF,value.var="iid")
data_xTZOLcSX<-dcast(b_indiv_test,id~xTZOLcSX,value.var="iid")
data_eWNUvdjK<-dcast(b_indiv_test,id~eWNUvdjK,value.var="iid")
data_yxQmKfsS<-dcast(b_indiv_test,id~yxQmKfsS,value.var="iid")
data_PyTDmsQl<-dcast(b_indiv_test,id~PyTDmsQl,value.var="iid")
data_CnQHDRVZ<-dcast(b_indiv_test,id~CnQHDRVZ,value.var="iid")
data_VxXEkbdS<-dcast(b_indiv_test,id~VxXEkbdS,value.var="iid")
data_vVyGhGoB<-dcast(b_indiv_test,id~vVyGhGoB,value.var="iid")
data_qRplnnEM<-dcast(b_indiv_test,id~qRplnnEM,value.var="iid")
data_SCLDdPrm<-dcast(b_indiv_test,id~SCLDdPrm,value.var="iid")
data_HcutWGCs<-dcast(b_indiv_test,id~HcutWGCs,value.var="iid")
data_GlkLFREL<-dcast(b_indiv_test,id~GlkLFREL,value.var="iid")
data_NAZxDkiV<-dcast(b_indiv_test,id~NAZxDkiV,value.var="iid")
data_yjAfWuLb<-dcast(b_indiv_test,id~yjAfWuLb,value.var="iid")
data_GlktDEEv<-dcast(b_indiv_test,id~GlktDEEv,value.var="iid")
data_IIvMcTrH<-dcast(b_indiv_test,id~IIvMcTrH,value.var="iid")
data_JbDBFPPd<-dcast(b_indiv_test,id~JbDBFPPd,value.var="iid")
data_clCRDApV<-dcast(b_indiv_test,id~clCRDApV,value.var="iid")
data_aYGuxgyP<-dcast(b_indiv_test,id~aYGuxgyP,value.var="iid")
data_NZYkmhkD<-dcast(b_indiv_test,id~NZYkmhkD,value.var="iid")
data_fxWioPPP<-dcast(b_indiv_test,id~fxWioPPP,value.var="iid")
data_DWmTWcUm<-dcast(b_indiv_test,id~DWmTWcUm,value.var="iid")
data_PxgyaWYq<-dcast(b_indiv_test,id~PxgyaWYq,value.var="iid")
data_cavdrXpj<-dcast(b_indiv_test,id~cavdrXpj,value.var="iid")


b_hhold_test<-merge(b_hhold_test,data_MmKGUOrD,by="id");rm(data_MmKGUOrD)
b_hhold_test<-merge(b_hhold_test,data_splgBZfe,by="id");rm(data_splgBZfe)
b_hhold_test<-merge(b_hhold_test,data_JTCCBpjX,by="id");rm(data_JTCCBpjX)
b_hhold_test<-merge(b_hhold_test,data_akGaJaYF,by="id");rm(data_akGaJaYF)
b_hhold_test<-merge(b_hhold_test,data_eYoMkEyN,by="id");rm(data_eYoMkEyN)
b_hhold_test<-merge(b_hhold_test,data_bmhTgzYu,by="id");rm(data_bmhTgzYu)
b_hhold_test<-merge(b_hhold_test,data_GjxOmHgp,by="id");rm(data_GjxOmHgp)
b_hhold_test<-merge(b_hhold_test,data_mYMBWfIH,by="id");rm(data_mYMBWfIH)
b_hhold_test<-merge(b_hhold_test,data_SZucUQmM,by="id");rm(data_SZucUQmM)
b_hhold_test<-merge(b_hhold_test,data_EfqFGRSF,by="id");rm(data_EfqFGRSF)
b_hhold_test<-merge(b_hhold_test,data_plDSQDzp,by="id");rm(data_plDSQDzp)
b_hhold_test<-merge(b_hhold_test,data_jyZvBZlo,by="id");rm(data_jyZvBZlo)
b_hhold_test<-merge(b_hhold_test,data_gyxBUEPe,by="id");rm(data_gyxBUEPe)
b_hhold_test<-merge(b_hhold_test,data_lTdxcpBA,by="id");rm(data_lTdxcpBA)
b_hhold_test<-merge(b_hhold_test,data_yoijDqAm,by="id");rm(data_yoijDqAm)
b_hhold_test<-merge(b_hhold_test,data_LkhgHzsx,by="id");rm(data_LkhgHzsx)
b_hhold_test<-merge(b_hhold_test,data_UUYXAsfo,by="id");rm(data_UUYXAsfo)
b_hhold_test<-merge(b_hhold_test,data_IPBrAaYt,by="id");rm(data_IPBrAaYt)
b_hhold_test<-merge(b_hhold_test,data_hCgDHGEc,by="id");rm(data_hCgDHGEc)
b_hhold_test<-merge(b_hhold_test,data_GFXSuQvB,by="id");rm(data_GFXSuQvB)
b_hhold_test<-merge(b_hhold_test,data_UPtsFglH,by="id");rm(data_UPtsFglH)
b_hhold_test<-merge(b_hhold_test,data_HZEsXrsF,by="id");rm(data_HZEsXrsF)
b_hhold_test<-merge(b_hhold_test,data_kgVoFHRj,by="id");rm(data_kgVoFHRj)
b_hhold_test<-merge(b_hhold_test,data_pqbNHKuK,by="id");rm(data_pqbNHKuK)
b_hhold_test<-merge(b_hhold_test,data_gEqzZWXR,by="id");rm(data_gEqzZWXR)
b_hhold_test<-merge(b_hhold_test,data_UkXhNUcd,by="id");rm(data_UkXhNUcd)
b_hhold_test<-merge(b_hhold_test,data_hggXZmdr,by="id");rm(data_hggXZmdr)
b_hhold_test<-merge(b_hhold_test,data_uyhBLPFL,by="id");rm(data_uyhBLPFL)
b_hhold_test<-merge(b_hhold_test,data_hwJpBxAl,by="id");rm(data_hwJpBxAl)
b_hhold_test<-merge(b_hhold_test,data_BXZfamTt,by="id");rm(data_BXZfamTt)
b_hhold_test<-merge(b_hhold_test,data_jkutpUMt,by="id");rm(data_jkutpUMt)
b_hhold_test<-merge(b_hhold_test,data_lFkBekuJ,by="id");rm(data_lFkBekuJ)
b_hhold_test<-merge(b_hhold_test,data_aTEyAdSs,by="id");rm(data_aTEyAdSs)
b_hhold_test<-merge(b_hhold_test,data_TdfmGIAn,by="id");rm(data_TdfmGIAn)
b_hhold_test<-merge(b_hhold_test,data_kaVnoUbJ,by="id");rm(data_kaVnoUbJ)
b_hhold_test<-merge(b_hhold_test,data_bngqQTHD,by="id");rm(data_bngqQTHD)
b_hhold_test<-merge(b_hhold_test,data_cRQWeYKZ,by="id");rm(data_cRQWeYKZ)
b_hhold_test<-merge(b_hhold_test,data_ErqgHOEp,by="id");rm(data_ErqgHOEp)
b_hhold_test<-merge(b_hhold_test,data_Ftzawcsw,by="id");rm(data_Ftzawcsw)
b_hhold_test<-merge(b_hhold_test,data_SlqMdbUr,by="id");rm(data_SlqMdbUr)
b_hhold_test<-merge(b_hhold_test,data_jyLFRgZs,by="id");rm(data_jyLFRgZs)
b_hhold_test<-merge(b_hhold_test,data_TsredPtf,by="id");rm(data_TsredPtf)
b_hhold_test<-merge(b_hhold_test,data_pFOEMbYu,by="id");rm(data_pFOEMbYu)
b_hhold_test<-merge(b_hhold_test,data_nOoTxqCQ,by="id");rm(data_nOoTxqCQ)
b_hhold_test<-merge(b_hhold_test,data_xohFWnds,by="id");rm(data_xohFWnds)
b_hhold_test<-merge(b_hhold_test,data_JYKPCImt,by="id");rm(data_JYKPCImt)
b_hhold_test<-merge(b_hhold_test,data_wEtnhPQs,by="id");rm(data_wEtnhPQs)
b_hhold_test<-merge(b_hhold_test,data_LIoTrAzw,by="id");rm(data_LIoTrAzw)
b_hhold_test<-merge(b_hhold_test,data_IoJgECCi,by="id");rm(data_IoJgECCi)
b_hhold_test<-merge(b_hhold_test,data_YwcPaCNf,by="id");rm(data_YwcPaCNf)
b_hhold_test<-merge(b_hhold_test,data_PgXpVWEU,by="id");rm(data_PgXpVWEU)
b_hhold_test<-merge(b_hhold_test,data_ENQEzjVj,by="id");rm(data_ENQEzjVj)
b_hhold_test<-merge(b_hhold_test,data_RFLvRzHv,by="id");rm(data_RFLvRzHv)
b_hhold_test<-merge(b_hhold_test,data_xhqvDVIs,by="id");rm(data_xhqvDVIs)
b_hhold_test<-merge(b_hhold_test,data_YhbMdUgd,by="id");rm(data_YhbMdUgd)
b_hhold_test<-merge(b_hhold_test,data_cPHgLSMk,by="id");rm(data_cPHgLSMk)
b_hhold_test<-merge(b_hhold_test,data_jBZoYONA,by="id");rm(data_jBZoYONA)
b_hhold_test<-merge(b_hhold_test,data_HHbZiXXp,by="id");rm(data_HHbZiXXp)
b_hhold_test<-merge(b_hhold_test,data_DsHJnzeZ,by="id");rm(data_DsHJnzeZ)
b_hhold_test<-merge(b_hhold_test,data_PwxicsdL,by="id");rm(data_PwxicsdL)
b_hhold_test<-merge(b_hhold_test,data_UZLkbGnz,by="id");rm(data_UZLkbGnz)
b_hhold_test<-merge(b_hhold_test,data_xNhKVNgq,by="id");rm(data_xNhKVNgq)
b_hhold_test<-merge(b_hhold_test,data_nIgKFReH,by="id");rm(data_nIgKFReH)
b_hhold_test<-merge(b_hhold_test,data_FgnMveDS,by="id");rm(data_FgnMveDS)
b_hhold_test<-merge(b_hhold_test,data_NdBZKehA,by="id");rm(data_NdBZKehA)
b_hhold_test<-merge(b_hhold_test,data_mlyFwTHy,by="id");rm(data_mlyFwTHy)
b_hhold_test<-merge(b_hhold_test,data_KjMhhJdX,by="id");rm(data_KjMhhJdX)
b_hhold_test<-merge(b_hhold_test,data_zXonuRgn,by="id");rm(data_zXonuRgn)
b_hhold_test<-merge(b_hhold_test,data_MWVlKQoo,by="id");rm(data_MWVlKQoo)
b_hhold_test<-merge(b_hhold_test,data_mQezyEOr,by="id");rm(data_mQezyEOr)
b_hhold_test<-merge(b_hhold_test,data_nPlbGBjS,by="id");rm(data_nPlbGBjS)
b_hhold_test<-merge(b_hhold_test,data_nmrQVORl,by="id");rm(data_nmrQVORl)
b_hhold_test<-merge(b_hhold_test,data_KGtdytLE,by="id");rm(data_KGtdytLE)
b_hhold_test<-merge(b_hhold_test,data_DELHTNkd,by="id");rm(data_DELHTNkd)
b_hhold_test<-merge(b_hhold_test,data_rZfVzfDA,by="id");rm(data_rZfVzfDA)
b_hhold_test<-merge(b_hhold_test,data_ZHOSEFIu,by="id");rm(data_ZHOSEFIu)
b_hhold_test<-merge(b_hhold_test,data_ogUWmSXZ,by="id");rm(data_ogUWmSXZ)
b_hhold_test<-merge(b_hhold_test,data_VWMwzteg,by="id");rm(data_VWMwzteg)
b_hhold_test<-merge(b_hhold_test,data_HaaXLOfY,by="id");rm(data_HaaXLOfY)
b_hhold_test<-merge(b_hhold_test,data_NCyUzkfp,by="id");rm(data_NCyUzkfp)
b_hhold_test<-merge(b_hhold_test,data_nAjgFRel,by="id");rm(data_nAjgFRel)
b_hhold_test<-merge(b_hhold_test,data_XZUEzGLM,by="id");rm(data_XZUEzGLM)
b_hhold_test<-merge(b_hhold_test,data_OFkIQOzS,by="id");rm(data_OFkIQOzS)
b_hhold_test<-merge(b_hhold_test,data_BqXRUQgi,by="id");rm(data_BqXRUQgi)
b_hhold_test<-merge(b_hhold_test,data_ywnHMkvq,by="id");rm(data_ywnHMkvq)
b_hhold_test<-merge(b_hhold_test,data_eKkwQtwX,by="id");rm(data_eKkwQtwX)
b_hhold_test<-merge(b_hhold_test,data_fwRLKHlN,by="id");rm(data_fwRLKHlN)
b_hhold_test<-merge(b_hhold_test,data_jUwlkffQ,by="id");rm(data_jUwlkffQ)
b_hhold_test<-merge(b_hhold_test,data_DAeoUuuN,by="id");rm(data_DAeoUuuN)
b_hhold_test<-merge(b_hhold_test,data_gsofZtJJ,by="id");rm(data_gsofZtJJ)
b_hhold_test<-merge(b_hhold_test,data_HQPtUibh,by="id");rm(data_HQPtUibh)
b_hhold_test<-merge(b_hhold_test,data_aqYWloSo,by="id");rm(data_aqYWloSo)
b_hhold_test<-merge(b_hhold_test,data_RUTkmJrl,by="id");rm(data_RUTkmJrl)
b_hhold_test<-merge(b_hhold_test,data_tQzcGkNE,by="id");rm(data_tQzcGkNE)
b_hhold_test<-merge(b_hhold_test,data_VszNwfYx,by="id");rm(data_VszNwfYx)
b_hhold_test<-merge(b_hhold_test,data_hnwVYJyV,by="id");rm(data_hnwVYJyV)
b_hhold_test<-merge(b_hhold_test,data_RsMBXisy,by="id");rm(data_RsMBXisy)
b_hhold_test<-merge(b_hhold_test,data_MiGIkxpV,by="id");rm(data_MiGIkxpV)
b_hhold_test<-merge(b_hhold_test,data_xbOnnZEV,by="id");rm(data_xbOnnZEV)
b_hhold_test<-merge(b_hhold_test,data_cGaHwCJA,by="id");rm(data_cGaHwCJA)
b_hhold_test<-merge(b_hhold_test,data_dfchpzYE,by="id");rm(data_dfchpzYE)
b_hhold_test<-merge(b_hhold_test,data_fwBNLzWK,by="id");rm(data_fwBNLzWK)
b_hhold_test<-merge(b_hhold_test,data_lLoRmWKX,by="id");rm(data_lLoRmWKX)
b_hhold_test<-merge(b_hhold_test,data_GhzvKcjl,by="id");rm(data_GhzvKcjl)
b_hhold_test<-merge(b_hhold_test,data_EpWsJmrF,by="id");rm(data_EpWsJmrF)
b_hhold_test<-merge(b_hhold_test,data_wpoJgbis,by="id");rm(data_wpoJgbis)
b_hhold_test<-merge(b_hhold_test,data_KyTRKtbW,by="id");rm(data_KyTRKtbW)
b_hhold_test<-merge(b_hhold_test,data_xlJGUBXM,by="id");rm(data_xlJGUBXM)
b_hhold_test<-merge(b_hhold_test,data_zuvYUDSL,by="id");rm(data_zuvYUDSL)
b_hhold_test<-merge(b_hhold_test,data_ozvFfhhM,by="id");rm(data_ozvFfhhM)
b_hhold_test<-merge(b_hhold_test,data_ljaNZowA,by="id");rm(data_ljaNZowA)
b_hhold_test<-merge(b_hhold_test,data_sbjoLEKh,by="id");rm(data_sbjoLEKh)
b_hhold_test<-merge(b_hhold_test,data_pyvZUOyi,by="id");rm(data_pyvZUOyi)
b_hhold_test<-merge(b_hhold_test,data_FldbnriM,by="id");rm(data_FldbnriM)
b_hhold_test<-merge(b_hhold_test,data_FyXQULwx,by="id");rm(data_FyXQULwx)
b_hhold_test<-merge(b_hhold_test,data_UUYYcars,by="id");rm(data_UUYYcars)
b_hhold_test<-merge(b_hhold_test,data_xMysunyA,by="id");rm(data_xMysunyA)
b_hhold_test<-merge(b_hhold_test,data_FOIfEcny,by="id");rm(data_FOIfEcny)
b_hhold_test<-merge(b_hhold_test,data_BhPvRtpj,by="id");rm(data_BhPvRtpj)
b_hhold_test<-merge(b_hhold_test,data_JniMXoSr,by="id");rm(data_JniMXoSr)
b_hhold_test<-merge(b_hhold_test,data_AFSIVjPG,by="id");rm(data_AFSIVjPG)
b_hhold_test<-merge(b_hhold_test,data_lnMlvpes,by="id");rm(data_lnMlvpes)
b_hhold_test<-merge(b_hhold_test,data_HrXGKbwr,by="id");rm(data_HrXGKbwr)
b_hhold_test<-merge(b_hhold_test,data_NUefhhHz,by="id");rm(data_NUefhhHz)
b_hhold_test<-merge(b_hhold_test,data_UaUnOdpg,by="id");rm(data_UaUnOdpg)
b_hhold_test<-merge(b_hhold_test,data_QIQcRKCg,by="id");rm(data_QIQcRKCg)
b_hhold_test<-merge(b_hhold_test,data_yNHqwYaJ,by="id");rm(data_yNHqwYaJ)
b_hhold_test<-merge(b_hhold_test,data_rWlPNhUy,by="id");rm(data_rWlPNhUy)
b_hhold_test<-merge(b_hhold_test,data_QcuPNLAv,by="id");rm(data_QcuPNLAv)
b_hhold_test<-merge(b_hhold_test,data_nkxrhykC,by="id");rm(data_nkxrhykC)
b_hhold_test<-merge(b_hhold_test,data_zTEEwTzG,by="id");rm(data_zTEEwTzG)
b_hhold_test<-merge(b_hhold_test,data_NMsLrKWd,by="id");rm(data_NMsLrKWd)
b_hhold_test<-merge(b_hhold_test,data_iHCKmQSy,by="id");rm(data_iHCKmQSy)
b_hhold_test<-merge(b_hhold_test,data_UPswDJlm,by="id");rm(data_UPswDJlm)
b_hhold_test<-merge(b_hhold_test,data_OhKTEjVy,by="id");rm(data_OhKTEjVy)
b_hhold_test<-merge(b_hhold_test,data_jRXAvmTH,by="id");rm(data_jRXAvmTH)
b_hhold_test<-merge(b_hhold_test,data_FHoVOXib,by="id");rm(data_FHoVOXib)
b_hhold_test<-merge(b_hhold_test,data_OATvAQNG,by="id");rm(data_OATvAQNG)
b_hhold_test<-merge(b_hhold_test,data_teSzyTms,by="id");rm(data_teSzyTms)
b_hhold_test<-merge(b_hhold_test,data_FsUFnmgF,by="id");rm(data_FsUFnmgF)
b_hhold_test<-merge(b_hhold_test,data_uDVGRBVU,by="id");rm(data_uDVGRBVU)
b_hhold_test<-merge(b_hhold_test,data_WCMouTCp,by="id");rm(data_WCMouTCp)
b_hhold_test<-merge(b_hhold_test,data_VKUGzaxx,by="id");rm(data_VKUGzaxx)
b_hhold_test<-merge(b_hhold_test,data_tkFVflRJ,by="id");rm(data_tkFVflRJ)
b_hhold_test<-merge(b_hhold_test,data_qhffLQpJ,by="id");rm(data_qhffLQpJ)
b_hhold_test<-merge(b_hhold_test,data_dFaxStnz,by="id");rm(data_dFaxStnz)
b_hhold_test<-merge(b_hhold_test,data_EzGVhUlW,by="id");rm(data_EzGVhUlW)
b_hhold_test<-merge(b_hhold_test,data_pDeMFniB,by="id");rm(data_pDeMFniB)
b_hhold_test<-merge(b_hhold_test,data_AxEjAWSE,by="id");rm(data_AxEjAWSE)
b_hhold_test<-merge(b_hhold_test,data_MhvfpnqH,by="id");rm(data_MhvfpnqH)
b_hhold_test<-merge(b_hhold_test,data_jdYXWZgD,by="id");rm(data_jdYXWZgD)
b_hhold_test<-merge(b_hhold_test,data_LLZtRxnK,by="id");rm(data_LLZtRxnK)
b_hhold_test<-merge(b_hhold_test,data_CtIAiLwz,by="id");rm(data_CtIAiLwz)
b_hhold_test<-merge(b_hhold_test,data_NPNqQdIn,by="id");rm(data_NPNqQdIn)
b_hhold_test<-merge(b_hhold_test,data_qzOZZsuS,by="id");rm(data_qzOZZsuS)
b_hhold_test<-merge(b_hhold_test,data_vquBDhol,by="id");rm(data_vquBDhol)
b_hhold_test<-merge(b_hhold_test,data_MMWrfMBi,by="id");rm(data_MMWrfMBi)
b_hhold_test<-merge(b_hhold_test,data_GshWgURK,by="id");rm(data_GshWgURK)
b_hhold_test<-merge(b_hhold_test,data_LSpCPhcU,by="id");rm(data_LSpCPhcU)
b_hhold_test<-merge(b_hhold_test,data_pHYVhLJD,by="id");rm(data_pHYVhLJD)
b_hhold_test<-merge(b_hhold_test,data_NocVJZYG,by="id");rm(data_NocVJZYG)
b_hhold_test<-merge(b_hhold_test,data_zhbhQewN,by="id");rm(data_zhbhQewN)
b_hhold_test<-merge(b_hhold_test,data_qxVAoxyX,by="id");rm(data_qxVAoxyX)
b_hhold_test<-merge(b_hhold_test,data_sWADnjxA,by="id");rm(data_sWADnjxA)
b_hhold_test<-merge(b_hhold_test,data_zgJdRdgg,by="id");rm(data_zgJdRdgg)
b_hhold_test<-merge(b_hhold_test,data_rxwugNti,by="id");rm(data_rxwugNti)
b_hhold_test<-merge(b_hhold_test,data_XIHNcHXI,by="id");rm(data_XIHNcHXI)
b_hhold_test<-merge(b_hhold_test,data_tugScLvF,by="id");rm(data_tugScLvF)
b_hhold_test<-merge(b_hhold_test,data_xTZOLcSX,by="id");rm(data_xTZOLcSX)
b_hhold_test<-merge(b_hhold_test,data_eWNUvdjK,by="id");rm(data_eWNUvdjK)
b_hhold_test<-merge(b_hhold_test,data_yxQmKfsS,by="id");rm(data_yxQmKfsS)
b_hhold_test<-merge(b_hhold_test,data_PyTDmsQl,by="id");rm(data_PyTDmsQl)
b_hhold_test<-merge(b_hhold_test,data_CnQHDRVZ,by="id");rm(data_CnQHDRVZ)
b_hhold_test<-merge(b_hhold_test,data_VxXEkbdS,by="id");rm(data_VxXEkbdS)
b_hhold_test<-merge(b_hhold_test,data_vVyGhGoB,by="id");rm(data_vVyGhGoB)
b_hhold_test<-merge(b_hhold_test,data_qRplnnEM,by="id");rm(data_qRplnnEM)
b_hhold_test<-merge(b_hhold_test,data_SCLDdPrm,by="id");rm(data_SCLDdPrm)
b_hhold_test<-merge(b_hhold_test,data_HcutWGCs,by="id");rm(data_HcutWGCs)
b_hhold_test<-merge(b_hhold_test,data_GlkLFREL,by="id");rm(data_GlkLFREL)
b_hhold_test<-merge(b_hhold_test,data_NAZxDkiV,by="id");rm(data_NAZxDkiV)
b_hhold_test<-merge(b_hhold_test,data_yjAfWuLb,by="id");rm(data_yjAfWuLb)
b_hhold_test<-merge(b_hhold_test,data_GlktDEEv,by="id");rm(data_GlktDEEv)
b_hhold_test<-merge(b_hhold_test,data_IIvMcTrH,by="id");rm(data_IIvMcTrH)
b_hhold_test<-merge(b_hhold_test,data_JbDBFPPd,by="id");rm(data_JbDBFPPd)
b_hhold_test<-merge(b_hhold_test,data_clCRDApV,by="id");rm(data_clCRDApV)
b_hhold_test<-merge(b_hhold_test,data_aYGuxgyP,by="id");rm(data_aYGuxgyP)
b_hhold_test<-merge(b_hhold_test,data_NZYkmhkD,by="id");rm(data_NZYkmhkD)
b_hhold_test<-merge(b_hhold_test,data_fxWioPPP,by="id");rm(data_fxWioPPP)
b_hhold_test<-merge(b_hhold_test,data_DWmTWcUm,by="id");rm(data_DWmTWcUm)
b_hhold_test<-merge(b_hhold_test,data_PxgyaWYq,by="id");rm(data_PxgyaWYq)
b_hhold_test<-merge(b_hhold_test,data_cavdrXpj,by="id");rm(data_cavdrXpj)



data_BoxViLPz<-aggregate(BoxViLPz~id,b_indiv_test,sum)
data_qlLzyqpP<-aggregate(qlLzyqpP~id,b_indiv_test,sum)
data_unRAgFtX<-aggregate(unRAgFtX~id,b_indiv_test,sum)
data_TJGiunYp<-aggregate(TJGiunYp~id,b_indiv_test,sum)
data_WmKLEUcd<-aggregate(WmKLEUcd~id,b_indiv_test,sum)
data_DYgxQeEi<-aggregate(DYgxQeEi~id,b_indiv_test,sum)
data_jfsTwowc<-aggregate(jfsTwowc~id,b_indiv_test,sum)
data_MGfpfHam<-aggregate(MGfpfHam~id,b_indiv_test,sum)
data_esHWAAyG<-aggregate(esHWAAyG~id,b_indiv_test,sum)
data_DtcKwIEv<-aggregate(DtcKwIEv~id,b_indiv_test,sum)
data_ETgxnJOM<-aggregate(ETgxnJOM~id,b_indiv_test,sum)
data_gKsBCLMY<-aggregate(gKsBCLMY~id,b_indiv_test,sum)
data_TZDgOhYY<-aggregate(TZDgOhYY~id,b_indiv_test,sum)
data_sWElQwuC<-aggregate(sWElQwuC~id,b_indiv_test,sum)
data_jzBRbsEG<-aggregate(jzBRbsEG~id,b_indiv_test,sum)
data_CLTXEwmz<-aggregate(CLTXEwmz~id,b_indiv_test,sum)
data_WqEZQuJP<-aggregate(WqEZQuJP~id,b_indiv_test,sum)
data_dnmwvCng<-aggregate(dnmwvCng~id,b_indiv_test,sum)
data_DSttkpSI<-aggregate(DSttkpSI~id,b_indiv_test,sum)
data_sIiSADFG<-aggregate(sIiSADFG~id,b_indiv_test,sum)
data_uDmhgsaQ<-aggregate(uDmhgsaQ~id,b_indiv_test,sum)
data_hdDTwJhQ<-aggregate(hdDTwJhQ~id,b_indiv_test,sum)
data_AJgudnHB<-aggregate(AJgudnHB~id,b_indiv_test,sum)
data_iZhWxnWa<-aggregate(iZhWxnWa~id,b_indiv_test,sum)
data_fyfDnyQk<-aggregate(fyfDnyQk~id,b_indiv_test,sum)
data_wJthinfa<-aggregate(wJthinfa~id,b_indiv_test,sum)
data_nxAFXxLQ<-aggregate(nxAFXxLQ~id,b_indiv_test,sum)
data_mAeaImix<-aggregate(mAeaImix~id,b_indiv_test,sum)
data_HZqPmvkr<-aggregate(HZqPmvkr~id,b_indiv_test,sum)
data_ulQCDoYe<-aggregate(ulQCDoYe~id,b_indiv_test,sum)
data_tzYvQeOb<-aggregate(tzYvQeOb~id,b_indiv_test,sum)
data_NfpXxGQk<-aggregate(NfpXxGQk~id,b_indiv_test,sum)



b_hhold_test<-merge(b_hhold_test,data_BoxViLPz,by="id",all.x = TRUE);rm(data_BoxViLPz)
b_hhold_test<-merge(b_hhold_test,data_qlLzyqpP,by="id",all.x = TRUE);rm(data_qlLzyqpP)
b_hhold_test<-merge(b_hhold_test,data_unRAgFtX,by="id",all.x = TRUE);rm(data_unRAgFtX)
b_hhold_test<-merge(b_hhold_test,data_TJGiunYp,by="id",all.x = TRUE);rm(data_TJGiunYp)
b_hhold_test<-merge(b_hhold_test,data_WmKLEUcd,by="id",all.x = TRUE);rm(data_WmKLEUcd)
b_hhold_test<-merge(b_hhold_test,data_DYgxQeEi,by="id",all.x = TRUE);rm(data_DYgxQeEi)
b_hhold_test<-merge(b_hhold_test,data_jfsTwowc,by="id",all.x = TRUE);rm(data_jfsTwowc)
b_hhold_test<-merge(b_hhold_test,data_MGfpfHam,by="id",all.x = TRUE);rm(data_MGfpfHam)
b_hhold_test<-merge(b_hhold_test,data_esHWAAyG,by="id",all.x = TRUE);rm(data_esHWAAyG)
b_hhold_test<-merge(b_hhold_test,data_DtcKwIEv,by="id",all.x = TRUE);rm(data_DtcKwIEv)
b_hhold_test<-merge(b_hhold_test,data_ETgxnJOM,by="id",all.x = TRUE);rm(data_ETgxnJOM)
b_hhold_test<-merge(b_hhold_test,data_gKsBCLMY,by="id",all.x = TRUE);rm(data_gKsBCLMY)
b_hhold_test<-merge(b_hhold_test,data_TZDgOhYY,by="id",all.x = TRUE);rm(data_TZDgOhYY)
b_hhold_test<-merge(b_hhold_test,data_sWElQwuC,by="id",all.x = TRUE);rm(data_sWElQwuC)
b_hhold_test<-merge(b_hhold_test,data_jzBRbsEG,by="id",all.x = TRUE);rm(data_jzBRbsEG)
b_hhold_test<-merge(b_hhold_test,data_CLTXEwmz,by="id",all.x = TRUE);rm(data_CLTXEwmz)
b_hhold_test<-merge(b_hhold_test,data_WqEZQuJP,by="id",all.x = TRUE);rm(data_WqEZQuJP)
b_hhold_test<-merge(b_hhold_test,data_dnmwvCng,by="id",all.x = TRUE);rm(data_dnmwvCng)
b_hhold_test<-merge(b_hhold_test,data_DSttkpSI,by="id",all.x = TRUE);rm(data_DSttkpSI)
b_hhold_test<-merge(b_hhold_test,data_sIiSADFG,by="id",all.x = TRUE);rm(data_sIiSADFG)
b_hhold_test<-merge(b_hhold_test,data_uDmhgsaQ,by="id",all.x = TRUE);rm(data_uDmhgsaQ)
b_hhold_test<-merge(b_hhold_test,data_hdDTwJhQ,by="id",all.x = TRUE);rm(data_hdDTwJhQ)
b_hhold_test<-merge(b_hhold_test,data_AJgudnHB,by="id",all.x = TRUE);rm(data_AJgudnHB)
b_hhold_test<-merge(b_hhold_test,data_iZhWxnWa,by="id",all.x = TRUE);rm(data_iZhWxnWa)
b_hhold_test<-merge(b_hhold_test,data_fyfDnyQk,by="id",all.x = TRUE);rm(data_fyfDnyQk)
b_hhold_test<-merge(b_hhold_test,data_wJthinfa,by="id",all.x = TRUE);rm(data_wJthinfa)
b_hhold_test<-merge(b_hhold_test,data_nxAFXxLQ,by="id",all.x = TRUE);rm(data_nxAFXxLQ)
b_hhold_test<-merge(b_hhold_test,data_mAeaImix,by="id",all.x = TRUE);rm(data_mAeaImix)
b_hhold_test<-merge(b_hhold_test,data_HZqPmvkr,by="id",all.x = TRUE);rm(data_HZqPmvkr)
b_hhold_test<-merge(b_hhold_test,data_ulQCDoYe,by="id",all.x = TRUE);rm(data_ulQCDoYe)
b_hhold_test<-merge(b_hhold_test,data_tzYvQeOb,by="id",all.x = TRUE);rm(data_tzYvQeOb)
b_hhold_test<-merge(b_hhold_test,data_NfpXxGQk,by="id",all.x = TRUE);rm(data_NfpXxGQk)


b_test<-b_hhold_test

b_test_cat<-sapply(b_test, is.factor)
b_test_cat<-b_test[,b_test_cat]
b_test_con<-sapply(b_test, is.numeric)
b_test_con<-b_test[,b_test_con]
b_test_dum<-dummy.data.frame(b_test_cat)
b_test_com<-cbind(b_test_con,b_test_dum)

rm(b_indiv_test);rm(b_hhold_test);rm(b_test);rm(b_test_cat);rm(b_test_con);rm(b_test_dum)

# RandomForest Model building ----------------------------------------------------------
set.seed(1234)
b_train_com[is.na(b_train_com)]<-0
fit <- randomForest(as.factor(poor) ~ ., data=b_train_com[-1],keep.forest=TRUE ,importance=TRUE,ntree=200)
#varImpPlot(fit)
pred <- predict(fit,b_train_com,type="prob")
MultiLogLoss(pred,b_train_com$poor)


###################################################################################
sum(is.na(b_train_com))
b_train_com[is.na(b_train_com)]<-0
tail(names(b_train_com))
prin_comp <- prcomp(b_train_com[,-c(1,1285)], scale. = T)
std_dev <- prin_comp$sdev
pr_var <- std_dev^2
pr_var[1:10]

prop_varex <- pr_var/sum(pr_var)
prop_varex[1:20]

plot(prop_varex, xlab = "Principal Component",
     ylab = "Proportion of Variance Explained",
     type = "b")

plot(cumsum(prop_varex), xlab = "Principal Component",
     ylab = "Cumulative Proportion of Variance Explained",
     type = "b")


train_data <- data.frame(poor = b_train_com$poor, prin_comp$x)
train_data <- train_data[,1:651]
table(train_data$poor)
train_data$poor<-ifelse(train_data$poor=="True",1,0)
train_data$poor<-as.factor(train_data$poor)

fit<-glm(poor~.,data = train_data,family = 'binomial')


test_data <- predict(prin_comp, newdata = b_test_com)
test_data <- as.data.frame(test_data)

test_data <- test_data[,1:651]
pred<-predict(fit,test_data,type = 'response')

B_subm<-data.frame(id=b_hhold_test$id,country=b_hhold_test$country,poor=pred)
write.csv(B_subm,'b_submit.csv',row.names = F)
MultiLogLoss(pred,train_data$poor)
head(test_data)
