library(reshape2)
head(a_indiv_test)
data_HeUgMnzF <- dcast(a_indiv_test , id ~ HeUgMnzF , value.var="iid")
data_CaukPfUC <- dcast(a_indiv_test , id ~ CaukPfUC , value.var="iid")
data_MzEtIdUF <- dcast(a_indiv_test , id ~ MzEtIdUF , value.var="iid")
data_gtnNTNam <- dcast(a_indiv_test , id ~ gtnNTNam , value.var="iid")
data_SWoXNmPc <- dcast(a_indiv_test , id ~ SWoXNmPc , value.var="iid")
data_eXbOkwhI <- dcast(a_indiv_test , id ~ eXbOkwhI , value.var="iid")
#data_OdXpbPGJ <- dcast(a_indiv_test , id ~ OdXpbPGJ , value.var="iid")
data_OdXpbPGJ<-aggregate(OdXpbPGJ~id,a_indiv_test,sum)
data_XONDGWjH <- dcast(a_indiv_test , id ~ XONDGWjH , value.var="iid")
data_KsFoQcUV <- dcast(a_indiv_test , id ~ KsFoQcUV , value.var="iid")
data_qYRZCuJD <- dcast(a_indiv_test , id ~ qYRZCuJD , value.var="iid")
data_FPQrjGnS <- dcast(a_indiv_test , id ~ FPQrjGnS , value.var="iid")
data_hOamrctW <- dcast(a_indiv_test , id ~ hOamrctW , value.var="iid")
data_XacGrSou <- dcast(a_indiv_test , id ~ XacGrSou , value.var="iid")
data_UsmeXdIS <- dcast(a_indiv_test , id ~ UsmeXdIS , value.var="iid")
data_igHwZsYz <- dcast(a_indiv_test , id ~ igHwZsYz , value.var="iid")
data_cxWuAOZv <- dcast(a_indiv_test , id ~ cxWuAOZv , value.var="iid")
data_AQpdiRUz <- dcast(a_indiv_test , id ~ AQpdiRUz , value.var="iid")
data_AoLwmlEH <- dcast(a_indiv_test , id ~ AoLwmlEH , value.var="iid")
data_nLUXHpZr <- dcast(a_indiv_test , id ~ nLUXHpZr , value.var="iid")
data_CRLlSiFu <- dcast(a_indiv_test , id ~ CRLlSiFu , value.var="iid")
data_jYpOAjPW <- dcast(a_indiv_test , id ~ jYpOAjPW , value.var="iid")
data_NAxEQZVi <- dcast(a_indiv_test , id ~ NAxEQZVi , value.var="iid")
data_QvgxCmCV <- dcast(a_indiv_test , id ~ QvgxCmCV , value.var="iid")
data_kvMGuSDN <- dcast(a_indiv_test , id ~ kvMGuSDN , value.var="iid")
data_AjYsrafY <- dcast(a_indiv_test , id ~ AjYsrafY , value.var="iid")
data_GNaMafZC <- dcast(a_indiv_test , id ~ GNaMafZC , value.var="iid")
data_zTLPJYTw <- dcast(a_indiv_test , id ~ zTLPJYTw , value.var="iid")
data_QKzxTGus <- dcast(a_indiv_test , id ~ QKzxTGus , value.var="iid")
data_SGeOiUlZ <- dcast(a_indiv_test , id ~ SGeOiUlZ , value.var="iid")
data_MUrHEJeh <- dcast(a_indiv_test , id ~ MUrHEJeh , value.var="iid")
data_XBldkztv <- dcast(a_indiv_test , id ~ XBldkztv , value.var="iid")
data_tbgZsPXD <- dcast(a_indiv_test , id ~ tbgZsPXD , value.var="iid")
#data_ukWqmeSS <- dcast(a_indiv_test , id ~ ukWqmeSS , value.var="iid")
data_ukWqmeSS<-aggregate(ukWqmeSS~id,a_indiv_test,sum)
data_qqVibbSA <- dcast(a_indiv_test , id ~ qqVibbSA , value.var="iid")
data_MgCoFhXK <- dcast(a_indiv_test , id ~ MgCoFhXK , value.var="iid")
data_rFpoTXAq <- dcast(a_indiv_test , id ~ rFpoTXAq , value.var="iid")
data_RXcLsVAQ <- dcast(a_indiv_test , id ~ RXcLsVAQ , value.var="iid")
data_rQWIpTiG <- dcast(a_indiv_test , id ~ rQWIpTiG , value.var="iid")
data_XizJGmbu <- dcast(a_indiv_test , id ~ XizJGmbu , value.var="iid")
data_xqUooaNJ <- dcast(a_indiv_test , id ~ xqUooaNJ , value.var="iid")
